// Code generated by ent, DO NOT EDIT.

package portfolio

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the portfolio type in the database.
	Label = "portfolio"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCoverURL holds the string denoting the cover_url field in the database.
	FieldCoverURL = "cover_url"
	// FieldProjectType holds the string denoting the project_type field in the database.
	FieldProjectType = "project_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDemoURL holds the string denoting the demo_url field in the database.
	FieldDemoURL = "demo_url"
	// FieldGithubURL holds the string denoting the github_url field in the database.
	FieldGithubURL = "github_url"
	// FieldFeatured holds the string denoting the featured field in the database.
	FieldFeatured = "featured"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldOverview holds the string denoting the overview field in the database.
	FieldOverview = "overview"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldClient holds the string denoting the client field in the database.
	FieldClient = "client"
	// FieldChallenge holds the string denoting the challenge field in the database.
	FieldChallenge = "challenge"
	// FieldSolution holds the string denoting the solution field in the database.
	FieldSolution = "solution"
	// FieldGalleryImages holds the string denoting the gallery_images field in the database.
	FieldGalleryImages = "gallery_images"
	// EdgeTechnologies holds the string denoting the technologies edge name in mutations.
	EdgeTechnologies = "technologies"
	// Table holds the table name of the portfolio in the database.
	Table = "portfolios"
	// TechnologiesTable is the table that holds the technologies relation/edge.
	TechnologiesTable = "portfolio_technologies"
	// TechnologiesInverseTable is the table name for the PortfolioTechnology entity.
	// It exists in this package in order to avoid circular dependency with the "portfoliotechnology" package.
	TechnologiesInverseTable = "portfolio_technologies"
	// TechnologiesColumn is the table column denoting the technologies relation/edge.
	TechnologiesColumn = "portfolio_technologies"
)

// Columns holds all SQL columns for portfolio fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTitle,
	FieldDescription,
	FieldCoverURL,
	FieldProjectType,
	FieldStatus,
	FieldDemoURL,
	FieldGithubURL,
	FieldFeatured,
	FieldSortOrder,
	FieldOverview,
	FieldRole,
	FieldDuration,
	FieldClient,
	FieldChallenge,
	FieldSolution,
	FieldGalleryImages,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/anzhiyu-c/anheyu-app/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DemoURLValidator is a validator for the "demo_url" field. It is called by the builders before save.
	DemoURLValidator func(string) error
	// GithubURLValidator is a validator for the "github_url" field. It is called by the builders before save.
	GithubURLValidator func(string) error
	// DefaultFeatured holds the default value on creation for the "featured" field.
	DefaultFeatured bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DurationValidator is a validator for the "duration" field. It is called by the builders before save.
	DurationValidator func(string) error
	// ClientValidator is a validator for the "client" field. It is called by the builders before save.
	ClientValidator func(string) error
)

// ProjectType defines the type for the "project_type" enum field.
type ProjectType string

// ProjectTypeOther is the default value of the ProjectType enum.
const DefaultProjectType = ProjectTypeOther

// ProjectType values.
const (
	ProjectTypeFrontend    ProjectType = "frontend"
	ProjectTypeVibecoding  ProjectType = "vibecoding"
	ProjectTypeFullstack   ProjectType = "fullstack"
	ProjectTypeMiniprogram ProjectType = "miniprogram"
	ProjectTypeApp         ProjectType = "app"
	ProjectTypeOther       ProjectType = "other"
)

func (pt ProjectType) String() string {
	return string(pt)
}

// ProjectTypeValidator is a validator for the "project_type" field enum values. It is called by the builders before save.
func ProjectTypeValidator(pt ProjectType) error {
	switch pt {
	case ProjectTypeFrontend, ProjectTypeVibecoding, ProjectTypeFullstack, ProjectTypeMiniprogram, ProjectTypeApp, ProjectTypeOther:
		return nil
	default:
		return fmt.Errorf("portfolio: invalid enum value for project_type field: %q", pt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusDeveloping is the default value of the Status enum.
const DefaultStatus = StatusDeveloping

// Status values.
const (
	StatusDeveloping Status = "developing"
	StatusCompleted  Status = "completed"
	StatusArchived   Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDeveloping, StatusCompleted, StatusArchived:
		return nil
	default:
		return fmt.Errorf("portfolio: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Portfolio queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCoverURL orders the results by the cover_url field.
func ByCoverURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverURL, opts...).ToFunc()
}

// ByProjectType orders the results by the project_type field.
func ByProjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDemoURL orders the results by the demo_url field.
func ByDemoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDemoURL, opts...).ToFunc()
}

// ByGithubURL orders the results by the github_url field.
func ByGithubURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubURL, opts...).ToFunc()
}

// ByFeatured orders the results by the featured field.
func ByFeatured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatured, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByOverview orders the results by the overview field.
func ByOverview(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverview, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByDuration orders the results by the duration field.
func ByDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuration, opts...).ToFunc()
}

// ByClient orders the results by the client field.
func ByClient(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClient, opts...).ToFunc()
}

// ByChallenge orders the results by the challenge field.
func ByChallenge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChallenge, opts...).ToFunc()
}

// BySolution orders the results by the solution field.
func BySolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSolution, opts...).ToFunc()
}

// ByTechnologiesCount orders the results by technologies count.
func ByTechnologiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTechnologiesStep(), opts...)
	}
}

// ByTechnologies orders the results by technologies terms.
func ByTechnologies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTechnologiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTechnologiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TechnologiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TechnologiesTable, TechnologiesColumn),
	)
}
