// Code generated by ent, DO NOT EDIT.

package portfolio

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldUpdatedAt, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDescription, v))
}

// CoverURL applies equality check predicate on the "cover_url" field. It's identical to CoverURLEQ.
func CoverURL(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCoverURL, v))
}

// DemoURL applies equality check predicate on the "demo_url" field. It's identical to DemoURLEQ.
func DemoURL(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDemoURL, v))
}

// GithubURL applies equality check predicate on the "github_url" field. It's identical to GithubURLEQ.
func GithubURL(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldGithubURL, v))
}

// Featured applies equality check predicate on the "featured" field. It's identical to FeaturedEQ.
func Featured(v bool) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldFeatured, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldSortOrder, v))
}

// Overview applies equality check predicate on the "overview" field. It's identical to OverviewEQ.
func Overview(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldOverview, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldRole, v))
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDuration, v))
}

// Client applies equality check predicate on the "client" field. It's identical to ClientEQ.
func Client(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldClient, v))
}

// Challenge applies equality check predicate on the "challenge" field. It's identical to ChallengeEQ.
func Challenge(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldChallenge, v))
}

// Solution applies equality check predicate on the "solution" field. It's identical to SolutionEQ.
func Solution(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldSolution, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldDescription, v))
}

// CoverURLEQ applies the EQ predicate on the "cover_url" field.
func CoverURLEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCoverURL, v))
}

// CoverURLNEQ applies the NEQ predicate on the "cover_url" field.
func CoverURLNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldCoverURL, v))
}

// CoverURLIn applies the In predicate on the "cover_url" field.
func CoverURLIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldCoverURL, vs...))
}

// CoverURLNotIn applies the NotIn predicate on the "cover_url" field.
func CoverURLNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldCoverURL, vs...))
}

// CoverURLGT applies the GT predicate on the "cover_url" field.
func CoverURLGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldCoverURL, v))
}

// CoverURLGTE applies the GTE predicate on the "cover_url" field.
func CoverURLGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldCoverURL, v))
}

// CoverURLLT applies the LT predicate on the "cover_url" field.
func CoverURLLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldCoverURL, v))
}

// CoverURLLTE applies the LTE predicate on the "cover_url" field.
func CoverURLLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldCoverURL, v))
}

// CoverURLContains applies the Contains predicate on the "cover_url" field.
func CoverURLContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldCoverURL, v))
}

// CoverURLHasPrefix applies the HasPrefix predicate on the "cover_url" field.
func CoverURLHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldCoverURL, v))
}

// CoverURLHasSuffix applies the HasSuffix predicate on the "cover_url" field.
func CoverURLHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldCoverURL, v))
}

// CoverURLIsNil applies the IsNil predicate on the "cover_url" field.
func CoverURLIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldCoverURL))
}

// CoverURLNotNil applies the NotNil predicate on the "cover_url" field.
func CoverURLNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldCoverURL))
}

// CoverURLEqualFold applies the EqualFold predicate on the "cover_url" field.
func CoverURLEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldCoverURL, v))
}

// CoverURLContainsFold applies the ContainsFold predicate on the "cover_url" field.
func CoverURLContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldCoverURL, v))
}

// ProjectTypeEQ applies the EQ predicate on the "project_type" field.
func ProjectTypeEQ(v ProjectType) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldProjectType, v))
}

// ProjectTypeNEQ applies the NEQ predicate on the "project_type" field.
func ProjectTypeNEQ(v ProjectType) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldProjectType, v))
}

// ProjectTypeIn applies the In predicate on the "project_type" field.
func ProjectTypeIn(vs ...ProjectType) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldProjectType, vs...))
}

// ProjectTypeNotIn applies the NotIn predicate on the "project_type" field.
func ProjectTypeNotIn(vs ...ProjectType) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldProjectType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldStatus, vs...))
}

// DemoURLEQ applies the EQ predicate on the "demo_url" field.
func DemoURLEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDemoURL, v))
}

// DemoURLNEQ applies the NEQ predicate on the "demo_url" field.
func DemoURLNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldDemoURL, v))
}

// DemoURLIn applies the In predicate on the "demo_url" field.
func DemoURLIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldDemoURL, vs...))
}

// DemoURLNotIn applies the NotIn predicate on the "demo_url" field.
func DemoURLNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldDemoURL, vs...))
}

// DemoURLGT applies the GT predicate on the "demo_url" field.
func DemoURLGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldDemoURL, v))
}

// DemoURLGTE applies the GTE predicate on the "demo_url" field.
func DemoURLGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldDemoURL, v))
}

// DemoURLLT applies the LT predicate on the "demo_url" field.
func DemoURLLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldDemoURL, v))
}

// DemoURLLTE applies the LTE predicate on the "demo_url" field.
func DemoURLLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldDemoURL, v))
}

// DemoURLContains applies the Contains predicate on the "demo_url" field.
func DemoURLContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldDemoURL, v))
}

// DemoURLHasPrefix applies the HasPrefix predicate on the "demo_url" field.
func DemoURLHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldDemoURL, v))
}

// DemoURLHasSuffix applies the HasSuffix predicate on the "demo_url" field.
func DemoURLHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldDemoURL, v))
}

// DemoURLIsNil applies the IsNil predicate on the "demo_url" field.
func DemoURLIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldDemoURL))
}

// DemoURLNotNil applies the NotNil predicate on the "demo_url" field.
func DemoURLNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldDemoURL))
}

// DemoURLEqualFold applies the EqualFold predicate on the "demo_url" field.
func DemoURLEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldDemoURL, v))
}

// DemoURLContainsFold applies the ContainsFold predicate on the "demo_url" field.
func DemoURLContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldDemoURL, v))
}

// GithubURLEQ applies the EQ predicate on the "github_url" field.
func GithubURLEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldGithubURL, v))
}

// GithubURLNEQ applies the NEQ predicate on the "github_url" field.
func GithubURLNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldGithubURL, v))
}

// GithubURLIn applies the In predicate on the "github_url" field.
func GithubURLIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldGithubURL, vs...))
}

// GithubURLNotIn applies the NotIn predicate on the "github_url" field.
func GithubURLNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldGithubURL, vs...))
}

// GithubURLGT applies the GT predicate on the "github_url" field.
func GithubURLGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldGithubURL, v))
}

// GithubURLGTE applies the GTE predicate on the "github_url" field.
func GithubURLGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldGithubURL, v))
}

// GithubURLLT applies the LT predicate on the "github_url" field.
func GithubURLLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldGithubURL, v))
}

// GithubURLLTE applies the LTE predicate on the "github_url" field.
func GithubURLLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldGithubURL, v))
}

// GithubURLContains applies the Contains predicate on the "github_url" field.
func GithubURLContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldGithubURL, v))
}

// GithubURLHasPrefix applies the HasPrefix predicate on the "github_url" field.
func GithubURLHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldGithubURL, v))
}

// GithubURLHasSuffix applies the HasSuffix predicate on the "github_url" field.
func GithubURLHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldGithubURL, v))
}

// GithubURLIsNil applies the IsNil predicate on the "github_url" field.
func GithubURLIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldGithubURL))
}

// GithubURLNotNil applies the NotNil predicate on the "github_url" field.
func GithubURLNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldGithubURL))
}

// GithubURLEqualFold applies the EqualFold predicate on the "github_url" field.
func GithubURLEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldGithubURL, v))
}

// GithubURLContainsFold applies the ContainsFold predicate on the "github_url" field.
func GithubURLContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldGithubURL, v))
}

// FeaturedEQ applies the EQ predicate on the "featured" field.
func FeaturedEQ(v bool) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldFeatured, v))
}

// FeaturedNEQ applies the NEQ predicate on the "featured" field.
func FeaturedNEQ(v bool) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldFeatured, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldSortOrder, v))
}

// OverviewEQ applies the EQ predicate on the "overview" field.
func OverviewEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldOverview, v))
}

// OverviewNEQ applies the NEQ predicate on the "overview" field.
func OverviewNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldOverview, v))
}

// OverviewIn applies the In predicate on the "overview" field.
func OverviewIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldOverview, vs...))
}

// OverviewNotIn applies the NotIn predicate on the "overview" field.
func OverviewNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldOverview, vs...))
}

// OverviewGT applies the GT predicate on the "overview" field.
func OverviewGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldOverview, v))
}

// OverviewGTE applies the GTE predicate on the "overview" field.
func OverviewGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldOverview, v))
}

// OverviewLT applies the LT predicate on the "overview" field.
func OverviewLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldOverview, v))
}

// OverviewLTE applies the LTE predicate on the "overview" field.
func OverviewLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldOverview, v))
}

// OverviewContains applies the Contains predicate on the "overview" field.
func OverviewContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldOverview, v))
}

// OverviewHasPrefix applies the HasPrefix predicate on the "overview" field.
func OverviewHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldOverview, v))
}

// OverviewHasSuffix applies the HasSuffix predicate on the "overview" field.
func OverviewHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldOverview, v))
}

// OverviewIsNil applies the IsNil predicate on the "overview" field.
func OverviewIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldOverview))
}

// OverviewNotNil applies the NotNil predicate on the "overview" field.
func OverviewNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldOverview))
}

// OverviewEqualFold applies the EqualFold predicate on the "overview" field.
func OverviewEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldOverview, v))
}

// OverviewContainsFold applies the ContainsFold predicate on the "overview" field.
func OverviewContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldOverview, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldRole, v))
}

// RoleIsNil applies the IsNil predicate on the "role" field.
func RoleIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldRole))
}

// RoleNotNil applies the NotNil predicate on the "role" field.
func RoleNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldRole))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldRole, v))
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDuration, v))
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldDuration, v))
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldDuration, vs...))
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldDuration, vs...))
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldDuration, v))
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldDuration, v))
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldDuration, v))
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldDuration, v))
}

// DurationContains applies the Contains predicate on the "duration" field.
func DurationContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldDuration, v))
}

// DurationHasPrefix applies the HasPrefix predicate on the "duration" field.
func DurationHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldDuration, v))
}

// DurationHasSuffix applies the HasSuffix predicate on the "duration" field.
func DurationHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldDuration, v))
}

// DurationIsNil applies the IsNil predicate on the "duration" field.
func DurationIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldDuration))
}

// DurationNotNil applies the NotNil predicate on the "duration" field.
func DurationNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldDuration))
}

// DurationEqualFold applies the EqualFold predicate on the "duration" field.
func DurationEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldDuration, v))
}

// DurationContainsFold applies the ContainsFold predicate on the "duration" field.
func DurationContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldDuration, v))
}

// ClientEQ applies the EQ predicate on the "client" field.
func ClientEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldClient, v))
}

// ClientNEQ applies the NEQ predicate on the "client" field.
func ClientNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldClient, v))
}

// ClientIn applies the In predicate on the "client" field.
func ClientIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldClient, vs...))
}

// ClientNotIn applies the NotIn predicate on the "client" field.
func ClientNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldClient, vs...))
}

// ClientGT applies the GT predicate on the "client" field.
func ClientGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldClient, v))
}

// ClientGTE applies the GTE predicate on the "client" field.
func ClientGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldClient, v))
}

// ClientLT applies the LT predicate on the "client" field.
func ClientLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldClient, v))
}

// ClientLTE applies the LTE predicate on the "client" field.
func ClientLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldClient, v))
}

// ClientContains applies the Contains predicate on the "client" field.
func ClientContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldClient, v))
}

// ClientHasPrefix applies the HasPrefix predicate on the "client" field.
func ClientHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldClient, v))
}

// ClientHasSuffix applies the HasSuffix predicate on the "client" field.
func ClientHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldClient, v))
}

// ClientIsNil applies the IsNil predicate on the "client" field.
func ClientIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldClient))
}

// ClientNotNil applies the NotNil predicate on the "client" field.
func ClientNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldClient))
}

// ClientEqualFold applies the EqualFold predicate on the "client" field.
func ClientEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldClient, v))
}

// ClientContainsFold applies the ContainsFold predicate on the "client" field.
func ClientContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldClient, v))
}

// ChallengeEQ applies the EQ predicate on the "challenge" field.
func ChallengeEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldChallenge, v))
}

// ChallengeNEQ applies the NEQ predicate on the "challenge" field.
func ChallengeNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldChallenge, v))
}

// ChallengeIn applies the In predicate on the "challenge" field.
func ChallengeIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldChallenge, vs...))
}

// ChallengeNotIn applies the NotIn predicate on the "challenge" field.
func ChallengeNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldChallenge, vs...))
}

// ChallengeGT applies the GT predicate on the "challenge" field.
func ChallengeGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldChallenge, v))
}

// ChallengeGTE applies the GTE predicate on the "challenge" field.
func ChallengeGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldChallenge, v))
}

// ChallengeLT applies the LT predicate on the "challenge" field.
func ChallengeLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldChallenge, v))
}

// ChallengeLTE applies the LTE predicate on the "challenge" field.
func ChallengeLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldChallenge, v))
}

// ChallengeContains applies the Contains predicate on the "challenge" field.
func ChallengeContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldChallenge, v))
}

// ChallengeHasPrefix applies the HasPrefix predicate on the "challenge" field.
func ChallengeHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldChallenge, v))
}

// ChallengeHasSuffix applies the HasSuffix predicate on the "challenge" field.
func ChallengeHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldChallenge, v))
}

// ChallengeIsNil applies the IsNil predicate on the "challenge" field.
func ChallengeIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldChallenge))
}

// ChallengeNotNil applies the NotNil predicate on the "challenge" field.
func ChallengeNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldChallenge))
}

// ChallengeEqualFold applies the EqualFold predicate on the "challenge" field.
func ChallengeEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldChallenge, v))
}

// ChallengeContainsFold applies the ContainsFold predicate on the "challenge" field.
func ChallengeContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldChallenge, v))
}

// SolutionEQ applies the EQ predicate on the "solution" field.
func SolutionEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldSolution, v))
}

// SolutionNEQ applies the NEQ predicate on the "solution" field.
func SolutionNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldSolution, v))
}

// SolutionIn applies the In predicate on the "solution" field.
func SolutionIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldSolution, vs...))
}

// SolutionNotIn applies the NotIn predicate on the "solution" field.
func SolutionNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldSolution, vs...))
}

// SolutionGT applies the GT predicate on the "solution" field.
func SolutionGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldSolution, v))
}

// SolutionGTE applies the GTE predicate on the "solution" field.
func SolutionGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldSolution, v))
}

// SolutionLT applies the LT predicate on the "solution" field.
func SolutionLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldSolution, v))
}

// SolutionLTE applies the LTE predicate on the "solution" field.
func SolutionLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldSolution, v))
}

// SolutionContains applies the Contains predicate on the "solution" field.
func SolutionContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldSolution, v))
}

// SolutionHasPrefix applies the HasPrefix predicate on the "solution" field.
func SolutionHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldSolution, v))
}

// SolutionHasSuffix applies the HasSuffix predicate on the "solution" field.
func SolutionHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldSolution, v))
}

// SolutionIsNil applies the IsNil predicate on the "solution" field.
func SolutionIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldSolution))
}

// SolutionNotNil applies the NotNil predicate on the "solution" field.
func SolutionNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldSolution))
}

// SolutionEqualFold applies the EqualFold predicate on the "solution" field.
func SolutionEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldSolution, v))
}

// SolutionContainsFold applies the ContainsFold predicate on the "solution" field.
func SolutionContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldSolution, v))
}

// GalleryImagesIsNil applies the IsNil predicate on the "gallery_images" field.
func GalleryImagesIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldGalleryImages))
}

// GalleryImagesNotNil applies the NotNil predicate on the "gallery_images" field.
func GalleryImagesNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldGalleryImages))
}

// HasTechnologies applies the HasEdge predicate on the "technologies" edge.
func HasTechnologies() predicate.Portfolio {
	return predicate.Portfolio(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TechnologiesTable, TechnologiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTechnologiesWith applies the HasEdge predicate on the "technologies" edge with a given conditions (other predicates).
func HasTechnologiesWith(preds ...predicate.PortfolioTechnology) predicate.Portfolio {
	return predicate.Portfolio(func(s *sql.Selector) {
		step := newTechnologiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Portfolio) predicate.Portfolio {
	return predicate.Portfolio(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Portfolio) predicate.Portfolio {
	return predicate.Portfolio(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Portfolio) predicate.Portfolio {
	return predicate.Portfolio(sql.NotPredicates(p))
}
