// Code generated by ent, DO NOT EDIT.

package portfoliotechnology

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the portfoliotechnology type in the database.
	Label = "portfolio_technology"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTechnology holds the string denoting the technology field in the database.
	FieldTechnology = "technology"
	// EdgePortfolio holds the string denoting the portfolio edge name in mutations.
	EdgePortfolio = "portfolio"
	// Table holds the table name of the portfoliotechnology in the database.
	Table = "portfolio_technologies"
	// PortfolioTable is the table that holds the portfolio relation/edge.
	PortfolioTable = "portfolio_technologies"
	// PortfolioInverseTable is the table name for the Portfolio entity.
	// It exists in this package in order to avoid circular dependency with the "portfolio" package.
	PortfolioInverseTable = "portfolios"
	// PortfolioColumn is the table column denoting the portfolio relation/edge.
	PortfolioColumn = "portfolio_technologies"
)

// Columns holds all SQL columns for portfoliotechnology fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTechnology,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "portfolio_technologies"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"portfolio_technologies",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/anzhiyu-c/anheyu-app/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TechnologyValidator is a validator for the "technology" field. It is called by the builders before save.
	TechnologyValidator func(string) error
)

// OrderOption defines the ordering options for the PortfolioTechnology queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTechnology orders the results by the technology field.
func ByTechnology(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTechnology, opts...).ToFunc()
}

// ByPortfolioField orders the results by portfolio field.
func ByPortfolioField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPortfolioStep(), sql.OrderByField(field, opts...))
	}
}
func newPortfolioStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PortfolioInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PortfolioTable, PortfolioColumn),
	)
}
