// Code generated by ent, DO NOT EDIT.

package portfoliotechnology

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldUpdatedAt, v))
}

// Technology applies equality check predicate on the "technology" field. It's identical to TechnologyEQ.
func Technology(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldTechnology, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLTE(FieldUpdatedAt, v))
}

// TechnologyEQ applies the EQ predicate on the "technology" field.
func TechnologyEQ(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEQ(FieldTechnology, v))
}

// TechnologyNEQ applies the NEQ predicate on the "technology" field.
func TechnologyNEQ(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNEQ(FieldTechnology, v))
}

// TechnologyIn applies the In predicate on the "technology" field.
func TechnologyIn(vs ...string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldIn(FieldTechnology, vs...))
}

// TechnologyNotIn applies the NotIn predicate on the "technology" field.
func TechnologyNotIn(vs ...string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldNotIn(FieldTechnology, vs...))
}

// TechnologyGT applies the GT predicate on the "technology" field.
func TechnologyGT(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGT(FieldTechnology, v))
}

// TechnologyGTE applies the GTE predicate on the "technology" field.
func TechnologyGTE(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldGTE(FieldTechnology, v))
}

// TechnologyLT applies the LT predicate on the "technology" field.
func TechnologyLT(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLT(FieldTechnology, v))
}

// TechnologyLTE applies the LTE predicate on the "technology" field.
func TechnologyLTE(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldLTE(FieldTechnology, v))
}

// TechnologyContains applies the Contains predicate on the "technology" field.
func TechnologyContains(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldContains(FieldTechnology, v))
}

// TechnologyHasPrefix applies the HasPrefix predicate on the "technology" field.
func TechnologyHasPrefix(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldHasPrefix(FieldTechnology, v))
}

// TechnologyHasSuffix applies the HasSuffix predicate on the "technology" field.
func TechnologyHasSuffix(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldHasSuffix(FieldTechnology, v))
}

// TechnologyEqualFold applies the EqualFold predicate on the "technology" field.
func TechnologyEqualFold(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldEqualFold(FieldTechnology, v))
}

// TechnologyContainsFold applies the ContainsFold predicate on the "technology" field.
func TechnologyContainsFold(v string) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.FieldContainsFold(FieldTechnology, v))
}

// HasPortfolio applies the HasEdge predicate on the "portfolio" edge.
func HasPortfolio() predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PortfolioTable, PortfolioColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPortfolioWith applies the HasEdge predicate on the "portfolio" edge with a given conditions (other predicates).
func HasPortfolioWith(preds ...predicate.Portfolio) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(func(s *sql.Selector) {
		step := newPortfolioStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PortfolioTechnology) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PortfolioTechnology) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PortfolioTechnology) predicate.PortfolioTechnology {
	return predicate.PortfolioTechnology(sql.NotPredicates(p))
}
