// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/portfolio"
	"github.com/anzhiyu-c/anheyu-app/ent/portfoliotechnology"
)

// PortfolioTechnologyCreate is the builder for creating a PortfolioTechnology entity.
type PortfolioTechnologyCreate struct {
	config
	mutation *PortfolioTechnologyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (ptc *PortfolioTechnologyCreate) SetDeletedAt(t time.Time) *PortfolioTechnologyCreate {
	ptc.mutation.SetDeletedAt(t)
	return ptc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ptc *PortfolioTechnologyCreate) SetNillableDeletedAt(t *time.Time) *PortfolioTechnologyCreate {
	if t != nil {
		ptc.SetDeletedAt(*t)
	}
	return ptc
}

// SetCreatedAt sets the "created_at" field.
func (ptc *PortfolioTechnologyCreate) SetCreatedAt(t time.Time) *PortfolioTechnologyCreate {
	ptc.mutation.SetCreatedAt(t)
	return ptc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ptc *PortfolioTechnologyCreate) SetNillableCreatedAt(t *time.Time) *PortfolioTechnologyCreate {
	if t != nil {
		ptc.SetCreatedAt(*t)
	}
	return ptc
}

// SetUpdatedAt sets the "updated_at" field.
func (ptc *PortfolioTechnologyCreate) SetUpdatedAt(t time.Time) *PortfolioTechnologyCreate {
	ptc.mutation.SetUpdatedAt(t)
	return ptc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ptc *PortfolioTechnologyCreate) SetNillableUpdatedAt(t *time.Time) *PortfolioTechnologyCreate {
	if t != nil {
		ptc.SetUpdatedAt(*t)
	}
	return ptc
}

// SetPortfolioID sets the "portfolio_id" field.
func (ptc *PortfolioTechnologyCreate) SetPortfolioID(u uint) *PortfolioTechnologyCreate {
	ptc.mutation.SetPortfolioID(u)
	return ptc
}

// SetTechnology sets the "technology" field.
func (ptc *PortfolioTechnologyCreate) SetTechnology(s string) *PortfolioTechnologyCreate {
	ptc.mutation.SetTechnology(s)
	return ptc
}

// SetID sets the "id" field.
func (ptc *PortfolioTechnologyCreate) SetID(u uint) *PortfolioTechnologyCreate {
	ptc.mutation.SetID(u)
	return ptc
}

// SetPortfolio sets the "portfolio" edge to the Portfolio entity.
func (ptc *PortfolioTechnologyCreate) SetPortfolio(p *Portfolio) *PortfolioTechnologyCreate {
	return ptc.SetPortfolioID(p.ID)
}

// Mutation returns the PortfolioTechnologyMutation object of the builder.
func (ptc *PortfolioTechnologyCreate) Mutation() *PortfolioTechnologyMutation {
	return ptc.mutation
}

// Save creates the PortfolioTechnology in the database.
func (ptc *PortfolioTechnologyCreate) Save(ctx context.Context) (*PortfolioTechnology, error) {
	if err := ptc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ptc.sqlSave, ptc.mutation, ptc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ptc *PortfolioTechnologyCreate) SaveX(ctx context.Context) *PortfolioTechnology {
	v, err := ptc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ptc *PortfolioTechnologyCreate) Exec(ctx context.Context) error {
	_, err := ptc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptc *PortfolioTechnologyCreate) ExecX(ctx context.Context) {
	if err := ptc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ptc *PortfolioTechnologyCreate) defaults() error {
	if _, ok := ptc.mutation.CreatedAt(); !ok {
		if portfoliotechnology.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized portfoliotechnology.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := portfoliotechnology.DefaultCreatedAt()
		ptc.mutation.SetCreatedAt(v)
	}
	if _, ok := ptc.mutation.UpdatedAt(); !ok {
		if portfoliotechnology.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized portfoliotechnology.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := portfoliotechnology.DefaultUpdatedAt()
		ptc.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ptc *PortfolioTechnologyCreate) check() error {
	if _, ok := ptc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PortfolioTechnology.created_at"`)}
	}
	if _, ok := ptc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PortfolioTechnology.updated_at"`)}
	}
	if _, ok := ptc.mutation.PortfolioID(); !ok {
		return &ValidationError{Name: "portfolio_id", err: errors.New(`ent: missing required field "PortfolioTechnology.portfolio_id"`)}
	}
	if _, ok := ptc.mutation.Technology(); !ok {
		return &ValidationError{Name: "technology", err: errors.New(`ent: missing required field "PortfolioTechnology.technology"`)}
	}
	if v, ok := ptc.mutation.Technology(); ok {
		if err := portfoliotechnology.TechnologyValidator(v); err != nil {
			return &ValidationError{Name: "technology", err: fmt.Errorf(`ent: validator failed for field "PortfolioTechnology.technology": %w`, err)}
		}
	}
	if len(ptc.mutation.PortfolioIDs()) == 0 {
		return &ValidationError{Name: "portfolio", err: errors.New(`ent: missing required edge "PortfolioTechnology.portfolio"`)}
	}
	return nil
}

func (ptc *PortfolioTechnologyCreate) sqlSave(ctx context.Context) (*PortfolioTechnology, error) {
	if err := ptc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ptc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ptc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	ptc.mutation.id = &_node.ID
	ptc.mutation.done = true
	return _node, nil
}

func (ptc *PortfolioTechnologyCreate) createSpec() (*PortfolioTechnology, *sqlgraph.CreateSpec) {
	var (
		_node = &PortfolioTechnology{config: ptc.config}
		_spec = sqlgraph.NewCreateSpec(portfoliotechnology.Table, sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint))
	)
	_spec.OnConflict = ptc.conflict
	if id, ok := ptc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ptc.mutation.DeletedAt(); ok {
		_spec.SetField(portfoliotechnology.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := ptc.mutation.CreatedAt(); ok {
		_spec.SetField(portfoliotechnology.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ptc.mutation.UpdatedAt(); ok {
		_spec.SetField(portfoliotechnology.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ptc.mutation.Technology(); ok {
		_spec.SetField(portfoliotechnology.FieldTechnology, field.TypeString, value)
		_node.Technology = value
	}
	if nodes := ptc.mutation.PortfolioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliotechnology.PortfolioTable,
			Columns: []string{portfoliotechnology.PortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PortfolioID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PortfolioTechnology.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PortfolioTechnologyUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (ptc *PortfolioTechnologyCreate) OnConflict(opts ...sql.ConflictOption) *PortfolioTechnologyUpsertOne {
	ptc.conflict = opts
	return &PortfolioTechnologyUpsertOne{
		create: ptc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PortfolioTechnology.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ptc *PortfolioTechnologyCreate) OnConflictColumns(columns ...string) *PortfolioTechnologyUpsertOne {
	ptc.conflict = append(ptc.conflict, sql.ConflictColumns(columns...))
	return &PortfolioTechnologyUpsertOne{
		create: ptc,
	}
}

type (
	// PortfolioTechnologyUpsertOne is the builder for "upsert"-ing
	//  one PortfolioTechnology node.
	PortfolioTechnologyUpsertOne struct {
		create *PortfolioTechnologyCreate
	}

	// PortfolioTechnologyUpsert is the "OnConflict" setter.
	PortfolioTechnologyUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *PortfolioTechnologyUpsert) SetDeletedAt(v time.Time) *PortfolioTechnologyUpsert {
	u.Set(portfoliotechnology.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsert) UpdateDeletedAt() *PortfolioTechnologyUpsert {
	u.SetExcluded(portfoliotechnology.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PortfolioTechnologyUpsert) ClearDeletedAt() *PortfolioTechnologyUpsert {
	u.SetNull(portfoliotechnology.FieldDeletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PortfolioTechnologyUpsert) SetUpdatedAt(v time.Time) *PortfolioTechnologyUpsert {
	u.Set(portfoliotechnology.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsert) UpdateUpdatedAt() *PortfolioTechnologyUpsert {
	u.SetExcluded(portfoliotechnology.FieldUpdatedAt)
	return u
}

// SetPortfolioID sets the "portfolio_id" field.
func (u *PortfolioTechnologyUpsert) SetPortfolioID(v uint) *PortfolioTechnologyUpsert {
	u.Set(portfoliotechnology.FieldPortfolioID, v)
	return u
}

// UpdatePortfolioID sets the "portfolio_id" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsert) UpdatePortfolioID() *PortfolioTechnologyUpsert {
	u.SetExcluded(portfoliotechnology.FieldPortfolioID)
	return u
}

// SetTechnology sets the "technology" field.
func (u *PortfolioTechnologyUpsert) SetTechnology(v string) *PortfolioTechnologyUpsert {
	u.Set(portfoliotechnology.FieldTechnology, v)
	return u
}

// UpdateTechnology sets the "technology" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsert) UpdateTechnology() *PortfolioTechnologyUpsert {
	u.SetExcluded(portfoliotechnology.FieldTechnology)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PortfolioTechnology.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(portfoliotechnology.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PortfolioTechnologyUpsertOne) UpdateNewValues() *PortfolioTechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(portfoliotechnology.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(portfoliotechnology.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PortfolioTechnology.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PortfolioTechnologyUpsertOne) Ignore() *PortfolioTechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PortfolioTechnologyUpsertOne) DoNothing() *PortfolioTechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PortfolioTechnologyCreate.OnConflict
// documentation for more info.
func (u *PortfolioTechnologyUpsertOne) Update(set func(*PortfolioTechnologyUpsert)) *PortfolioTechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PortfolioTechnologyUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PortfolioTechnologyUpsertOne) SetDeletedAt(v time.Time) *PortfolioTechnologyUpsertOne {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsertOne) UpdateDeletedAt() *PortfolioTechnologyUpsertOne {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PortfolioTechnologyUpsertOne) ClearDeletedAt() *PortfolioTechnologyUpsertOne {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PortfolioTechnologyUpsertOne) SetUpdatedAt(v time.Time) *PortfolioTechnologyUpsertOne {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsertOne) UpdateUpdatedAt() *PortfolioTechnologyUpsertOne {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPortfolioID sets the "portfolio_id" field.
func (u *PortfolioTechnologyUpsertOne) SetPortfolioID(v uint) *PortfolioTechnologyUpsertOne {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.SetPortfolioID(v)
	})
}

// UpdatePortfolioID sets the "portfolio_id" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsertOne) UpdatePortfolioID() *PortfolioTechnologyUpsertOne {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.UpdatePortfolioID()
	})
}

// SetTechnology sets the "technology" field.
func (u *PortfolioTechnologyUpsertOne) SetTechnology(v string) *PortfolioTechnologyUpsertOne {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.SetTechnology(v)
	})
}

// UpdateTechnology sets the "technology" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsertOne) UpdateTechnology() *PortfolioTechnologyUpsertOne {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.UpdateTechnology()
	})
}

// Exec executes the query.
func (u *PortfolioTechnologyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PortfolioTechnologyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PortfolioTechnologyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PortfolioTechnologyUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PortfolioTechnologyUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PortfolioTechnologyCreateBulk is the builder for creating many PortfolioTechnology entities in bulk.
type PortfolioTechnologyCreateBulk struct {
	config
	err      error
	builders []*PortfolioTechnologyCreate
	conflict []sql.ConflictOption
}

// Save creates the PortfolioTechnology entities in the database.
func (ptcb *PortfolioTechnologyCreateBulk) Save(ctx context.Context) ([]*PortfolioTechnology, error) {
	if ptcb.err != nil {
		return nil, ptcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ptcb.builders))
	nodes := make([]*PortfolioTechnology, len(ptcb.builders))
	mutators := make([]Mutator, len(ptcb.builders))
	for i := range ptcb.builders {
		func(i int, root context.Context) {
			builder := ptcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PortfolioTechnologyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ptcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ptcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ptcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ptcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ptcb *PortfolioTechnologyCreateBulk) SaveX(ctx context.Context) []*PortfolioTechnology {
	v, err := ptcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ptcb *PortfolioTechnologyCreateBulk) Exec(ctx context.Context) error {
	_, err := ptcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptcb *PortfolioTechnologyCreateBulk) ExecX(ctx context.Context) {
	if err := ptcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PortfolioTechnology.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PortfolioTechnologyUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (ptcb *PortfolioTechnologyCreateBulk) OnConflict(opts ...sql.ConflictOption) *PortfolioTechnologyUpsertBulk {
	ptcb.conflict = opts
	return &PortfolioTechnologyUpsertBulk{
		create: ptcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PortfolioTechnology.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ptcb *PortfolioTechnologyCreateBulk) OnConflictColumns(columns ...string) *PortfolioTechnologyUpsertBulk {
	ptcb.conflict = append(ptcb.conflict, sql.ConflictColumns(columns...))
	return &PortfolioTechnologyUpsertBulk{
		create: ptcb,
	}
}

// PortfolioTechnologyUpsertBulk is the builder for "upsert"-ing
// a bulk of PortfolioTechnology nodes.
type PortfolioTechnologyUpsertBulk struct {
	create *PortfolioTechnologyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PortfolioTechnology.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(portfoliotechnology.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PortfolioTechnologyUpsertBulk) UpdateNewValues() *PortfolioTechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(portfoliotechnology.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(portfoliotechnology.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PortfolioTechnology.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PortfolioTechnologyUpsertBulk) Ignore() *PortfolioTechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PortfolioTechnologyUpsertBulk) DoNothing() *PortfolioTechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PortfolioTechnologyCreateBulk.OnConflict
// documentation for more info.
func (u *PortfolioTechnologyUpsertBulk) Update(set func(*PortfolioTechnologyUpsert)) *PortfolioTechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PortfolioTechnologyUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PortfolioTechnologyUpsertBulk) SetDeletedAt(v time.Time) *PortfolioTechnologyUpsertBulk {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsertBulk) UpdateDeletedAt() *PortfolioTechnologyUpsertBulk {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PortfolioTechnologyUpsertBulk) ClearDeletedAt() *PortfolioTechnologyUpsertBulk {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PortfolioTechnologyUpsertBulk) SetUpdatedAt(v time.Time) *PortfolioTechnologyUpsertBulk {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsertBulk) UpdateUpdatedAt() *PortfolioTechnologyUpsertBulk {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPortfolioID sets the "portfolio_id" field.
func (u *PortfolioTechnologyUpsertBulk) SetPortfolioID(v uint) *PortfolioTechnologyUpsertBulk {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.SetPortfolioID(v)
	})
}

// UpdatePortfolioID sets the "portfolio_id" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsertBulk) UpdatePortfolioID() *PortfolioTechnologyUpsertBulk {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.UpdatePortfolioID()
	})
}

// SetTechnology sets the "technology" field.
func (u *PortfolioTechnologyUpsertBulk) SetTechnology(v string) *PortfolioTechnologyUpsertBulk {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.SetTechnology(v)
	})
}

// UpdateTechnology sets the "technology" field to the value that was provided on create.
func (u *PortfolioTechnologyUpsertBulk) UpdateTechnology() *PortfolioTechnologyUpsertBulk {
	return u.Update(func(s *PortfolioTechnologyUpsert) {
		s.UpdateTechnology()
	})
}

// Exec executes the query.
func (u *PortfolioTechnologyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PortfolioTechnologyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PortfolioTechnologyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PortfolioTechnologyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
