// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/portfolio"
	"github.com/anzhiyu-c/anheyu-app/pkg/domain/model"
)

// 项目作品集表
type Portfolio struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 项目标题
	Title string `json:"title,omitempty"`
	// 项目简介
	Description string `json:"description,omitempty"`
	// 封面图URL
	CoverURL string `json:"cover_url,omitempty"`
	// 项目层级: normal-普通, recommended-推荐, featured-精选
	Tier portfolio.Tier `json:"tier,omitempty"`
	// 项目类型
	ProjectType portfolio.ProjectType `json:"project_type,omitempty"`
	// 项目状态
	Status portfolio.Status `json:"status,omitempty"`
	// 演示地址
	DemoURL string `json:"demo_url,omitempty"`
	// GitHub地址
	GithubURL string `json:"github_url,omitempty"`
	// 是否精选
	Featured bool `json:"featured,omitempty"`
	// 排序权重
	SortOrder int `json:"sort_order,omitempty"`
	// 项目概述
	Overview string `json:"overview,omitempty"`
	// 担任角色
	Role string `json:"role,omitempty"`
	// 项目周期
	Duration string `json:"duration,omitempty"`
	// 所属客户
	Client string `json:"client,omitempty"`
	// 挑战描述
	Challenge string `json:"challenge,omitempty"`
	// 解决方案
	Solution string `json:"solution,omitempty"`
	// 图库图片URL列表
	GalleryImages []model.GalleryImage `json:"gallery_images,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PortfolioQuery when eager-loading is set.
	Edges        PortfolioEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PortfolioEdges holds the relations/edges for other nodes in the graph.
type PortfolioEdges struct {
	// Technologies holds the value of the technologies edge.
	Technologies []*PortfolioTechnology `json:"technologies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TechnologiesOrErr returns the Technologies value or an error if the edge
// was not loaded in eager-loading.
func (e PortfolioEdges) TechnologiesOrErr() ([]*PortfolioTechnology, error) {
	if e.loadedTypes[0] {
		return e.Technologies, nil
	}
	return nil, &NotLoadedError{edge: "technologies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Portfolio) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case portfolio.FieldGalleryImages:
			values[i] = new([]byte)
		case portfolio.FieldFeatured:
			values[i] = new(sql.NullBool)
		case portfolio.FieldID, portfolio.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case portfolio.FieldTitle, portfolio.FieldDescription, portfolio.FieldCoverURL, portfolio.FieldTier, portfolio.FieldProjectType, portfolio.FieldStatus, portfolio.FieldDemoURL, portfolio.FieldGithubURL, portfolio.FieldOverview, portfolio.FieldRole, portfolio.FieldDuration, portfolio.FieldClient, portfolio.FieldChallenge, portfolio.FieldSolution:
			values[i] = new(sql.NullString)
		case portfolio.FieldDeletedAt, portfolio.FieldCreatedAt, portfolio.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Portfolio fields.
func (po *Portfolio) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case portfolio.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			po.ID = uint(value.Int64)
		case portfolio.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				po.DeletedAt = new(time.Time)
				*po.DeletedAt = value.Time
			}
		case portfolio.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				po.CreatedAt = value.Time
			}
		case portfolio.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				po.UpdatedAt = value.Time
			}
		case portfolio.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				po.Title = value.String
			}
		case portfolio.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				po.Description = value.String
			}
		case portfolio.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				po.CoverURL = value.String
			}
		case portfolio.FieldTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[i])
			} else if value.Valid {
				po.Tier = portfolio.Tier(value.String)
			}
		case portfolio.FieldProjectType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_type", values[i])
			} else if value.Valid {
				po.ProjectType = portfolio.ProjectType(value.String)
			}
		case portfolio.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				po.Status = portfolio.Status(value.String)
			}
		case portfolio.FieldDemoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field demo_url", values[i])
			} else if value.Valid {
				po.DemoURL = value.String
			}
		case portfolio.FieldGithubURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field github_url", values[i])
			} else if value.Valid {
				po.GithubURL = value.String
			}
		case portfolio.FieldFeatured:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field featured", values[i])
			} else if value.Valid {
				po.Featured = value.Bool
			}
		case portfolio.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				po.SortOrder = int(value.Int64)
			}
		case portfolio.FieldOverview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overview", values[i])
			} else if value.Valid {
				po.Overview = value.String
			}
		case portfolio.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				po.Role = value.String
			}
		case portfolio.FieldDuration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field duration", values[i])
			} else if value.Valid {
				po.Duration = value.String
			}
		case portfolio.FieldClient:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client", values[i])
			} else if value.Valid {
				po.Client = value.String
			}
		case portfolio.FieldChallenge:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field challenge", values[i])
			} else if value.Valid {
				po.Challenge = value.String
			}
		case portfolio.FieldSolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field solution", values[i])
			} else if value.Valid {
				po.Solution = value.String
			}
		case portfolio.FieldGalleryImages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field gallery_images", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &po.GalleryImages); err != nil {
					return fmt.Errorf("unmarshal field gallery_images: %w", err)
				}
			}
		default:
			po.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Portfolio.
// This includes values selected through modifiers, order, etc.
func (po *Portfolio) Value(name string) (ent.Value, error) {
	return po.selectValues.Get(name)
}

// QueryTechnologies queries the "technologies" edge of the Portfolio entity.
func (po *Portfolio) QueryTechnologies() *PortfolioTechnologyQuery {
	return NewPortfolioClient(po.config).QueryTechnologies(po)
}

// Update returns a builder for updating this Portfolio.
// Note that you need to call Portfolio.Unwrap() before calling this method if this Portfolio
// was returned from a transaction, and the transaction was committed or rolled back.
func (po *Portfolio) Update() *PortfolioUpdateOne {
	return NewPortfolioClient(po.config).UpdateOne(po)
}

// Unwrap unwraps the Portfolio entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (po *Portfolio) Unwrap() *Portfolio {
	_tx, ok := po.config.driver.(*txDriver)
	if !ok {
		panic("ent: Portfolio is not a transactional entity")
	}
	po.config.driver = _tx.drv
	return po
}

// String implements the fmt.Stringer.
func (po *Portfolio) String() string {
	var builder strings.Builder
	builder.WriteString("Portfolio(")
	builder.WriteString(fmt.Sprintf("id=%v, ", po.ID))
	if v := po.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(po.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(po.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(po.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(po.Description)
	builder.WriteString(", ")
	builder.WriteString("cover_url=")
	builder.WriteString(po.CoverURL)
	builder.WriteString(", ")
	builder.WriteString("tier=")
	builder.WriteString(fmt.Sprintf("%v", po.Tier))
	builder.WriteString(", ")
	builder.WriteString("project_type=")
	builder.WriteString(fmt.Sprintf("%v", po.ProjectType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", po.Status))
	builder.WriteString(", ")
	builder.WriteString("demo_url=")
	builder.WriteString(po.DemoURL)
	builder.WriteString(", ")
	builder.WriteString("github_url=")
	builder.WriteString(po.GithubURL)
	builder.WriteString(", ")
	builder.WriteString("featured=")
	builder.WriteString(fmt.Sprintf("%v", po.Featured))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", po.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("overview=")
	builder.WriteString(po.Overview)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(po.Role)
	builder.WriteString(", ")
	builder.WriteString("duration=")
	builder.WriteString(po.Duration)
	builder.WriteString(", ")
	builder.WriteString("client=")
	builder.WriteString(po.Client)
	builder.WriteString(", ")
	builder.WriteString("challenge=")
	builder.WriteString(po.Challenge)
	builder.WriteString(", ")
	builder.WriteString("solution=")
	builder.WriteString(po.Solution)
	builder.WriteString(", ")
	builder.WriteString("gallery_images=")
	builder.WriteString(fmt.Sprintf("%v", po.GalleryImages))
	builder.WriteByte(')')
	return builder.String()
}

// Portfolios is a parsable slice of Portfolio.
type Portfolios []*Portfolio
