// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/portfolio"
	"github.com/anzhiyu-c/anheyu-app/ent/portfoliotechnology"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// PortfolioTechnologyQuery is the builder for querying PortfolioTechnology entities.
type PortfolioTechnologyQuery struct {
	config
	ctx           *QueryContext
	order         []portfoliotechnology.OrderOption
	inters        []Interceptor
	predicates    []predicate.PortfolioTechnology
	withPortfolio *PortfolioQuery
	withFKs       bool
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PortfolioTechnologyQuery builder.
func (ptq *PortfolioTechnologyQuery) Where(ps ...predicate.PortfolioTechnology) *PortfolioTechnologyQuery {
	ptq.predicates = append(ptq.predicates, ps...)
	return ptq
}

// Limit the number of records to be returned by this query.
func (ptq *PortfolioTechnologyQuery) Limit(limit int) *PortfolioTechnologyQuery {
	ptq.ctx.Limit = &limit
	return ptq
}

// Offset to start from.
func (ptq *PortfolioTechnologyQuery) Offset(offset int) *PortfolioTechnologyQuery {
	ptq.ctx.Offset = &offset
	return ptq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ptq *PortfolioTechnologyQuery) Unique(unique bool) *PortfolioTechnologyQuery {
	ptq.ctx.Unique = &unique
	return ptq
}

// Order specifies how the records should be ordered.
func (ptq *PortfolioTechnologyQuery) Order(o ...portfoliotechnology.OrderOption) *PortfolioTechnologyQuery {
	ptq.order = append(ptq.order, o...)
	return ptq
}

// QueryPortfolio chains the current query on the "portfolio" edge.
func (ptq *PortfolioTechnologyQuery) QueryPortfolio() *PortfolioQuery {
	query := (&PortfolioClient{config: ptq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ptq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(portfoliotechnology.Table, portfoliotechnology.FieldID, selector),
			sqlgraph.To(portfolio.Table, portfolio.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, portfoliotechnology.PortfolioTable, portfoliotechnology.PortfolioColumn),
		)
		fromU = sqlgraph.SetNeighbors(ptq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PortfolioTechnology entity from the query.
// Returns a *NotFoundError when no PortfolioTechnology was found.
func (ptq *PortfolioTechnologyQuery) First(ctx context.Context) (*PortfolioTechnology, error) {
	nodes, err := ptq.Limit(1).All(setContextOp(ctx, ptq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{portfoliotechnology.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ptq *PortfolioTechnologyQuery) FirstX(ctx context.Context) *PortfolioTechnology {
	node, err := ptq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PortfolioTechnology ID from the query.
// Returns a *NotFoundError when no PortfolioTechnology ID was found.
func (ptq *PortfolioTechnologyQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = ptq.Limit(1).IDs(setContextOp(ctx, ptq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{portfoliotechnology.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ptq *PortfolioTechnologyQuery) FirstIDX(ctx context.Context) uint {
	id, err := ptq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PortfolioTechnology entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PortfolioTechnology entity is found.
// Returns a *NotFoundError when no PortfolioTechnology entities are found.
func (ptq *PortfolioTechnologyQuery) Only(ctx context.Context) (*PortfolioTechnology, error) {
	nodes, err := ptq.Limit(2).All(setContextOp(ctx, ptq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{portfoliotechnology.Label}
	default:
		return nil, &NotSingularError{portfoliotechnology.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ptq *PortfolioTechnologyQuery) OnlyX(ctx context.Context) *PortfolioTechnology {
	node, err := ptq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PortfolioTechnology ID in the query.
// Returns a *NotSingularError when more than one PortfolioTechnology ID is found.
// Returns a *NotFoundError when no entities are found.
func (ptq *PortfolioTechnologyQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = ptq.Limit(2).IDs(setContextOp(ctx, ptq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{portfoliotechnology.Label}
	default:
		err = &NotSingularError{portfoliotechnology.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ptq *PortfolioTechnologyQuery) OnlyIDX(ctx context.Context) uint {
	id, err := ptq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PortfolioTechnologies.
func (ptq *PortfolioTechnologyQuery) All(ctx context.Context) ([]*PortfolioTechnology, error) {
	ctx = setContextOp(ctx, ptq.ctx, ent.OpQueryAll)
	if err := ptq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PortfolioTechnology, *PortfolioTechnologyQuery]()
	return withInterceptors[[]*PortfolioTechnology](ctx, ptq, qr, ptq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ptq *PortfolioTechnologyQuery) AllX(ctx context.Context) []*PortfolioTechnology {
	nodes, err := ptq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PortfolioTechnology IDs.
func (ptq *PortfolioTechnologyQuery) IDs(ctx context.Context) (ids []uint, err error) {
	if ptq.ctx.Unique == nil && ptq.path != nil {
		ptq.Unique(true)
	}
	ctx = setContextOp(ctx, ptq.ctx, ent.OpQueryIDs)
	if err = ptq.Select(portfoliotechnology.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ptq *PortfolioTechnologyQuery) IDsX(ctx context.Context) []uint {
	ids, err := ptq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ptq *PortfolioTechnologyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ptq.ctx, ent.OpQueryCount)
	if err := ptq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ptq, querierCount[*PortfolioTechnologyQuery](), ptq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ptq *PortfolioTechnologyQuery) CountX(ctx context.Context) int {
	count, err := ptq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ptq *PortfolioTechnologyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ptq.ctx, ent.OpQueryExist)
	switch _, err := ptq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ptq *PortfolioTechnologyQuery) ExistX(ctx context.Context) bool {
	exist, err := ptq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PortfolioTechnologyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ptq *PortfolioTechnologyQuery) Clone() *PortfolioTechnologyQuery {
	if ptq == nil {
		return nil
	}
	return &PortfolioTechnologyQuery{
		config:        ptq.config,
		ctx:           ptq.ctx.Clone(),
		order:         append([]portfoliotechnology.OrderOption{}, ptq.order...),
		inters:        append([]Interceptor{}, ptq.inters...),
		predicates:    append([]predicate.PortfolioTechnology{}, ptq.predicates...),
		withPortfolio: ptq.withPortfolio.Clone(),
		// clone intermediate query.
		sql:       ptq.sql.Clone(),
		path:      ptq.path,
		modifiers: append([]func(*sql.Selector){}, ptq.modifiers...),
	}
}

// WithPortfolio tells the query-builder to eager-load the nodes that are connected to
// the "portfolio" edge. The optional arguments are used to configure the query builder of the edge.
func (ptq *PortfolioTechnologyQuery) WithPortfolio(opts ...func(*PortfolioQuery)) *PortfolioTechnologyQuery {
	query := (&PortfolioClient{config: ptq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ptq.withPortfolio = query
	return ptq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deleted_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PortfolioTechnology.Query().
//		GroupBy(portfoliotechnology.FieldDeletedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ptq *PortfolioTechnologyQuery) GroupBy(field string, fields ...string) *PortfolioTechnologyGroupBy {
	ptq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PortfolioTechnologyGroupBy{build: ptq}
	grbuild.flds = &ptq.ctx.Fields
	grbuild.label = portfoliotechnology.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deleted_at,omitempty"`
//	}
//
//	client.PortfolioTechnology.Query().
//		Select(portfoliotechnology.FieldDeletedAt).
//		Scan(ctx, &v)
func (ptq *PortfolioTechnologyQuery) Select(fields ...string) *PortfolioTechnologySelect {
	ptq.ctx.Fields = append(ptq.ctx.Fields, fields...)
	sbuild := &PortfolioTechnologySelect{PortfolioTechnologyQuery: ptq}
	sbuild.label = portfoliotechnology.Label
	sbuild.flds, sbuild.scan = &ptq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PortfolioTechnologySelect configured with the given aggregations.
func (ptq *PortfolioTechnologyQuery) Aggregate(fns ...AggregateFunc) *PortfolioTechnologySelect {
	return ptq.Select().Aggregate(fns...)
}

func (ptq *PortfolioTechnologyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ptq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ptq); err != nil {
				return err
			}
		}
	}
	for _, f := range ptq.ctx.Fields {
		if !portfoliotechnology.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ptq.path != nil {
		prev, err := ptq.path(ctx)
		if err != nil {
			return err
		}
		ptq.sql = prev
	}
	return nil
}

func (ptq *PortfolioTechnologyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PortfolioTechnology, error) {
	var (
		nodes       = []*PortfolioTechnology{}
		withFKs     = ptq.withFKs
		_spec       = ptq.querySpec()
		loadedTypes = [1]bool{
			ptq.withPortfolio != nil,
		}
	)
	if ptq.withPortfolio != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, portfoliotechnology.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PortfolioTechnology).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PortfolioTechnology{config: ptq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ptq.modifiers) > 0 {
		_spec.Modifiers = ptq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ptq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ptq.withPortfolio; query != nil {
		if err := ptq.loadPortfolio(ctx, query, nodes, nil,
			func(n *PortfolioTechnology, e *Portfolio) { n.Edges.Portfolio = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ptq *PortfolioTechnologyQuery) loadPortfolio(ctx context.Context, query *PortfolioQuery, nodes []*PortfolioTechnology, init func(*PortfolioTechnology), assign func(*PortfolioTechnology, *Portfolio)) error {
	ids := make([]uint, 0, len(nodes))
	nodeids := make(map[uint][]*PortfolioTechnology)
	for i := range nodes {
		if nodes[i].portfolio_technologies == nil {
			continue
		}
		fk := *nodes[i].portfolio_technologies
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(portfolio.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "portfolio_technologies" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ptq *PortfolioTechnologyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ptq.querySpec()
	if len(ptq.modifiers) > 0 {
		_spec.Modifiers = ptq.modifiers
	}
	_spec.Node.Columns = ptq.ctx.Fields
	if len(ptq.ctx.Fields) > 0 {
		_spec.Unique = ptq.ctx.Unique != nil && *ptq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ptq.driver, _spec)
}

func (ptq *PortfolioTechnologyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(portfoliotechnology.Table, portfoliotechnology.Columns, sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint))
	_spec.From = ptq.sql
	if unique := ptq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ptq.path != nil {
		_spec.Unique = true
	}
	if fields := ptq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portfoliotechnology.FieldID)
		for i := range fields {
			if fields[i] != portfoliotechnology.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ptq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ptq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ptq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ptq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ptq *PortfolioTechnologyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ptq.driver.Dialect())
	t1 := builder.Table(portfoliotechnology.Table)
	columns := ptq.ctx.Fields
	if len(columns) == 0 {
		columns = portfoliotechnology.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ptq.sql != nil {
		selector = ptq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ptq.ctx.Unique != nil && *ptq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ptq.modifiers {
		m(selector)
	}
	for _, p := range ptq.predicates {
		p(selector)
	}
	for _, p := range ptq.order {
		p(selector)
	}
	if offset := ptq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ptq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ptq *PortfolioTechnologyQuery) Modify(modifiers ...func(s *sql.Selector)) *PortfolioTechnologySelect {
	ptq.modifiers = append(ptq.modifiers, modifiers...)
	return ptq.Select()
}

// PortfolioTechnologyGroupBy is the group-by builder for PortfolioTechnology entities.
type PortfolioTechnologyGroupBy struct {
	selector
	build *PortfolioTechnologyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ptgb *PortfolioTechnologyGroupBy) Aggregate(fns ...AggregateFunc) *PortfolioTechnologyGroupBy {
	ptgb.fns = append(ptgb.fns, fns...)
	return ptgb
}

// Scan applies the selector query and scans the result into the given value.
func (ptgb *PortfolioTechnologyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ptgb.build.ctx, ent.OpQueryGroupBy)
	if err := ptgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PortfolioTechnologyQuery, *PortfolioTechnologyGroupBy](ctx, ptgb.build, ptgb, ptgb.build.inters, v)
}

func (ptgb *PortfolioTechnologyGroupBy) sqlScan(ctx context.Context, root *PortfolioTechnologyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ptgb.fns))
	for _, fn := range ptgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ptgb.flds)+len(ptgb.fns))
		for _, f := range *ptgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ptgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ptgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PortfolioTechnologySelect is the builder for selecting fields of PortfolioTechnology entities.
type PortfolioTechnologySelect struct {
	*PortfolioTechnologyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pts *PortfolioTechnologySelect) Aggregate(fns ...AggregateFunc) *PortfolioTechnologySelect {
	pts.fns = append(pts.fns, fns...)
	return pts
}

// Scan applies the selector query and scans the result into the given value.
func (pts *PortfolioTechnologySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pts.ctx, ent.OpQuerySelect)
	if err := pts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PortfolioTechnologyQuery, *PortfolioTechnologySelect](ctx, pts.PortfolioTechnologyQuery, pts, pts.inters, v)
}

func (pts *PortfolioTechnologySelect) sqlScan(ctx context.Context, root *PortfolioTechnologyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pts.fns))
	for _, fn := range pts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pts *PortfolioTechnologySelect) Modify(modifiers ...func(s *sql.Selector)) *PortfolioTechnologySelect {
	pts.modifiers = append(pts.modifiers, modifiers...)
	return pts
}
