// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/portfoliotechnology"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// PortfolioTechnologyDelete is the builder for deleting a PortfolioTechnology entity.
type PortfolioTechnologyDelete struct {
	config
	hooks    []Hook
	mutation *PortfolioTechnologyMutation
}

// Where appends a list predicates to the PortfolioTechnologyDelete builder.
func (ptd *PortfolioTechnologyDelete) Where(ps ...predicate.PortfolioTechnology) *PortfolioTechnologyDelete {
	ptd.mutation.Where(ps...)
	return ptd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ptd *PortfolioTechnologyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ptd.sqlExec, ptd.mutation, ptd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ptd *PortfolioTechnologyDelete) ExecX(ctx context.Context) int {
	n, err := ptd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ptd *PortfolioTechnologyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(portfoliotechnology.Table, sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint))
	if ps := ptd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ptd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ptd.mutation.done = true
	return affected, err
}

// PortfolioTechnologyDeleteOne is the builder for deleting a single PortfolioTechnology entity.
type PortfolioTechnologyDeleteOne struct {
	ptd *PortfolioTechnologyDelete
}

// Where appends a list predicates to the PortfolioTechnologyDelete builder.
func (ptdo *PortfolioTechnologyDeleteOne) Where(ps ...predicate.PortfolioTechnology) *PortfolioTechnologyDeleteOne {
	ptdo.ptd.mutation.Where(ps...)
	return ptdo
}

// Exec executes the deletion query.
func (ptdo *PortfolioTechnologyDeleteOne) Exec(ctx context.Context) error {
	n, err := ptdo.ptd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{portfoliotechnology.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ptdo *PortfolioTechnologyDeleteOne) ExecX(ctx context.Context) {
	if err := ptdo.Exec(ctx); err != nil {
		panic(err)
	}
}
