// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/portfolio"
	"github.com/anzhiyu-c/anheyu-app/ent/portfoliotechnology"
)

// 项目技术栈表
type PortfolioTechnology struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 所属作品ID
	PortfolioID uint `json:"portfolio_id,omitempty"`
	// 技术名称
	Technology string `json:"technology,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PortfolioTechnologyQuery when eager-loading is set.
	Edges        PortfolioTechnologyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PortfolioTechnologyEdges holds the relations/edges for other nodes in the graph.
type PortfolioTechnologyEdges struct {
	// Portfolio holds the value of the portfolio edge.
	Portfolio *Portfolio `json:"portfolio,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PortfolioOrErr returns the Portfolio value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PortfolioTechnologyEdges) PortfolioOrErr() (*Portfolio, error) {
	if e.Portfolio != nil {
		return e.Portfolio, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: portfolio.Label}
	}
	return nil, &NotLoadedError{edge: "portfolio"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PortfolioTechnology) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case portfoliotechnology.FieldID, portfoliotechnology.FieldPortfolioID:
			values[i] = new(sql.NullInt64)
		case portfoliotechnology.FieldTechnology:
			values[i] = new(sql.NullString)
		case portfoliotechnology.FieldDeletedAt, portfoliotechnology.FieldCreatedAt, portfoliotechnology.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PortfolioTechnology fields.
func (pt *PortfolioTechnology) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case portfoliotechnology.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pt.ID = uint(value.Int64)
		case portfoliotechnology.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				pt.DeletedAt = new(time.Time)
				*pt.DeletedAt = value.Time
			}
		case portfoliotechnology.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pt.CreatedAt = value.Time
			}
		case portfoliotechnology.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pt.UpdatedAt = value.Time
			}
		case portfoliotechnology.FieldPortfolioID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field portfolio_id", values[i])
			} else if value.Valid {
				pt.PortfolioID = uint(value.Int64)
			}
		case portfoliotechnology.FieldTechnology:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field technology", values[i])
			} else if value.Valid {
				pt.Technology = value.String
			}
		default:
			pt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PortfolioTechnology.
// This includes values selected through modifiers, order, etc.
func (pt *PortfolioTechnology) Value(name string) (ent.Value, error) {
	return pt.selectValues.Get(name)
}

// QueryPortfolio queries the "portfolio" edge of the PortfolioTechnology entity.
func (pt *PortfolioTechnology) QueryPortfolio() *PortfolioQuery {
	return NewPortfolioTechnologyClient(pt.config).QueryPortfolio(pt)
}

// Update returns a builder for updating this PortfolioTechnology.
// Note that you need to call PortfolioTechnology.Unwrap() before calling this method if this PortfolioTechnology
// was returned from a transaction, and the transaction was committed or rolled back.
func (pt *PortfolioTechnology) Update() *PortfolioTechnologyUpdateOne {
	return NewPortfolioTechnologyClient(pt.config).UpdateOne(pt)
}

// Unwrap unwraps the PortfolioTechnology entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pt *PortfolioTechnology) Unwrap() *PortfolioTechnology {
	_tx, ok := pt.config.driver.(*txDriver)
	if !ok {
		panic("ent: PortfolioTechnology is not a transactional entity")
	}
	pt.config.driver = _tx.drv
	return pt
}

// String implements the fmt.Stringer.
func (pt *PortfolioTechnology) String() string {
	var builder strings.Builder
	builder.WriteString("PortfolioTechnology(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pt.ID))
	if v := pt.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pt.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pt.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("portfolio_id=")
	builder.WriteString(fmt.Sprintf("%v", pt.PortfolioID))
	builder.WriteString(", ")
	builder.WriteString("technology=")
	builder.WriteString(pt.Technology)
	builder.WriteByte(')')
	return builder.String()
}

// PortfolioTechnologies is a parsable slice of PortfolioTechnology.
type PortfolioTechnologies []*PortfolioTechnology
