// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/portfolio"
	"github.com/anzhiyu-c/anheyu-app/ent/portfoliotechnology"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// PortfolioUpdate is the builder for updating Portfolio entities.
type PortfolioUpdate struct {
	config
	hooks     []Hook
	mutation  *PortfolioMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PortfolioUpdate builder.
func (pu *PortfolioUpdate) Where(ps ...predicate.Portfolio) *PortfolioUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetDeletedAt sets the "deleted_at" field.
func (pu *PortfolioUpdate) SetDeletedAt(t time.Time) *PortfolioUpdate {
	pu.mutation.SetDeletedAt(t)
	return pu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableDeletedAt(t *time.Time) *PortfolioUpdate {
	if t != nil {
		pu.SetDeletedAt(*t)
	}
	return pu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pu *PortfolioUpdate) ClearDeletedAt() *PortfolioUpdate {
	pu.mutation.ClearDeletedAt()
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *PortfolioUpdate) SetUpdatedAt(t time.Time) *PortfolioUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetTitle sets the "title" field.
func (pu *PortfolioUpdate) SetTitle(s string) *PortfolioUpdate {
	pu.mutation.SetTitle(s)
	return pu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableTitle(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetTitle(*s)
	}
	return pu
}

// SetDescription sets the "description" field.
func (pu *PortfolioUpdate) SetDescription(s string) *PortfolioUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableDescription(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// ClearDescription clears the value of the "description" field.
func (pu *PortfolioUpdate) ClearDescription() *PortfolioUpdate {
	pu.mutation.ClearDescription()
	return pu
}

// SetCoverURL sets the "cover_url" field.
func (pu *PortfolioUpdate) SetCoverURL(s string) *PortfolioUpdate {
	pu.mutation.SetCoverURL(s)
	return pu
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableCoverURL(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetCoverURL(*s)
	}
	return pu
}

// ClearCoverURL clears the value of the "cover_url" field.
func (pu *PortfolioUpdate) ClearCoverURL() *PortfolioUpdate {
	pu.mutation.ClearCoverURL()
	return pu
}

// SetProjectType sets the "project_type" field.
func (pu *PortfolioUpdate) SetProjectType(pt portfolio.ProjectType) *PortfolioUpdate {
	pu.mutation.SetProjectType(pt)
	return pu
}

// SetNillableProjectType sets the "project_type" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableProjectType(pt *portfolio.ProjectType) *PortfolioUpdate {
	if pt != nil {
		pu.SetProjectType(*pt)
	}
	return pu
}

// SetStatus sets the "status" field.
func (pu *PortfolioUpdate) SetStatus(po portfolio.Status) *PortfolioUpdate {
	pu.mutation.SetStatus(po)
	return pu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableStatus(po *portfolio.Status) *PortfolioUpdate {
	if po != nil {
		pu.SetStatus(*po)
	}
	return pu
}

// SetDemoURL sets the "demo_url" field.
func (pu *PortfolioUpdate) SetDemoURL(s string) *PortfolioUpdate {
	pu.mutation.SetDemoURL(s)
	return pu
}

// SetNillableDemoURL sets the "demo_url" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableDemoURL(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetDemoURL(*s)
	}
	return pu
}

// ClearDemoURL clears the value of the "demo_url" field.
func (pu *PortfolioUpdate) ClearDemoURL() *PortfolioUpdate {
	pu.mutation.ClearDemoURL()
	return pu
}

// SetGithubURL sets the "github_url" field.
func (pu *PortfolioUpdate) SetGithubURL(s string) *PortfolioUpdate {
	pu.mutation.SetGithubURL(s)
	return pu
}

// SetNillableGithubURL sets the "github_url" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableGithubURL(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetGithubURL(*s)
	}
	return pu
}

// ClearGithubURL clears the value of the "github_url" field.
func (pu *PortfolioUpdate) ClearGithubURL() *PortfolioUpdate {
	pu.mutation.ClearGithubURL()
	return pu
}

// SetFeatured sets the "featured" field.
func (pu *PortfolioUpdate) SetFeatured(b bool) *PortfolioUpdate {
	pu.mutation.SetFeatured(b)
	return pu
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableFeatured(b *bool) *PortfolioUpdate {
	if b != nil {
		pu.SetFeatured(*b)
	}
	return pu
}

// SetSortOrder sets the "sort_order" field.
func (pu *PortfolioUpdate) SetSortOrder(i int) *PortfolioUpdate {
	pu.mutation.ResetSortOrder()
	pu.mutation.SetSortOrder(i)
	return pu
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableSortOrder(i *int) *PortfolioUpdate {
	if i != nil {
		pu.SetSortOrder(*i)
	}
	return pu
}

// AddSortOrder adds i to the "sort_order" field.
func (pu *PortfolioUpdate) AddSortOrder(i int) *PortfolioUpdate {
	pu.mutation.AddSortOrder(i)
	return pu
}

// SetOverview sets the "overview" field.
func (pu *PortfolioUpdate) SetOverview(s string) *PortfolioUpdate {
	pu.mutation.SetOverview(s)
	return pu
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableOverview(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetOverview(*s)
	}
	return pu
}

// ClearOverview clears the value of the "overview" field.
func (pu *PortfolioUpdate) ClearOverview() *PortfolioUpdate {
	pu.mutation.ClearOverview()
	return pu
}

// SetRole sets the "role" field.
func (pu *PortfolioUpdate) SetRole(s string) *PortfolioUpdate {
	pu.mutation.SetRole(s)
	return pu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableRole(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetRole(*s)
	}
	return pu
}

// ClearRole clears the value of the "role" field.
func (pu *PortfolioUpdate) ClearRole() *PortfolioUpdate {
	pu.mutation.ClearRole()
	return pu
}

// SetDuration sets the "duration" field.
func (pu *PortfolioUpdate) SetDuration(s string) *PortfolioUpdate {
	pu.mutation.SetDuration(s)
	return pu
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableDuration(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetDuration(*s)
	}
	return pu
}

// ClearDuration clears the value of the "duration" field.
func (pu *PortfolioUpdate) ClearDuration() *PortfolioUpdate {
	pu.mutation.ClearDuration()
	return pu
}

// SetClient sets the "client" field.
func (pu *PortfolioUpdate) SetClient(s string) *PortfolioUpdate {
	pu.mutation.SetClient(s)
	return pu
}

// SetNillableClient sets the "client" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableClient(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetClient(*s)
	}
	return pu
}

// ClearClient clears the value of the "client" field.
func (pu *PortfolioUpdate) ClearClient() *PortfolioUpdate {
	pu.mutation.ClearClient()
	return pu
}

// SetChallenge sets the "challenge" field.
func (pu *PortfolioUpdate) SetChallenge(s string) *PortfolioUpdate {
	pu.mutation.SetChallenge(s)
	return pu
}

// SetNillableChallenge sets the "challenge" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableChallenge(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetChallenge(*s)
	}
	return pu
}

// ClearChallenge clears the value of the "challenge" field.
func (pu *PortfolioUpdate) ClearChallenge() *PortfolioUpdate {
	pu.mutation.ClearChallenge()
	return pu
}

// SetSolution sets the "solution" field.
func (pu *PortfolioUpdate) SetSolution(s string) *PortfolioUpdate {
	pu.mutation.SetSolution(s)
	return pu
}

// SetNillableSolution sets the "solution" field if the given value is not nil.
func (pu *PortfolioUpdate) SetNillableSolution(s *string) *PortfolioUpdate {
	if s != nil {
		pu.SetSolution(*s)
	}
	return pu
}

// ClearSolution clears the value of the "solution" field.
func (pu *PortfolioUpdate) ClearSolution() *PortfolioUpdate {
	pu.mutation.ClearSolution()
	return pu
}

// SetGalleryImages sets the "gallery_images" field.
func (pu *PortfolioUpdate) SetGalleryImages(s []string) *PortfolioUpdate {
	pu.mutation.SetGalleryImages(s)
	return pu
}

// AppendGalleryImages appends s to the "gallery_images" field.
func (pu *PortfolioUpdate) AppendGalleryImages(s []string) *PortfolioUpdate {
	pu.mutation.AppendGalleryImages(s)
	return pu
}

// ClearGalleryImages clears the value of the "gallery_images" field.
func (pu *PortfolioUpdate) ClearGalleryImages() *PortfolioUpdate {
	pu.mutation.ClearGalleryImages()
	return pu
}

// AddTechnologyIDs adds the "technologies" edge to the PortfolioTechnology entity by IDs.
func (pu *PortfolioUpdate) AddTechnologyIDs(ids ...uint) *PortfolioUpdate {
	pu.mutation.AddTechnologyIDs(ids...)
	return pu
}

// AddTechnologies adds the "technologies" edges to the PortfolioTechnology entity.
func (pu *PortfolioUpdate) AddTechnologies(p ...*PortfolioTechnology) *PortfolioUpdate {
	ids := make([]uint, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddTechnologyIDs(ids...)
}

// Mutation returns the PortfolioMutation object of the builder.
func (pu *PortfolioUpdate) Mutation() *PortfolioMutation {
	return pu.mutation
}

// ClearTechnologies clears all "technologies" edges to the PortfolioTechnology entity.
func (pu *PortfolioUpdate) ClearTechnologies() *PortfolioUpdate {
	pu.mutation.ClearTechnologies()
	return pu
}

// RemoveTechnologyIDs removes the "technologies" edge to PortfolioTechnology entities by IDs.
func (pu *PortfolioUpdate) RemoveTechnologyIDs(ids ...uint) *PortfolioUpdate {
	pu.mutation.RemoveTechnologyIDs(ids...)
	return pu
}

// RemoveTechnologies removes "technologies" edges to PortfolioTechnology entities.
func (pu *PortfolioUpdate) RemoveTechnologies(p ...*PortfolioTechnology) *PortfolioUpdate {
	ids := make([]uint, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemoveTechnologyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PortfolioUpdate) Save(ctx context.Context) (int, error) {
	if err := pu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PortfolioUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PortfolioUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PortfolioUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PortfolioUpdate) defaults() error {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		if portfolio.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized portfolio.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := portfolio.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pu *PortfolioUpdate) check() error {
	if v, ok := pu.mutation.Title(); ok {
		if err := portfolio.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Portfolio.title": %w`, err)}
		}
	}
	if v, ok := pu.mutation.ProjectType(); ok {
		if err := portfolio.ProjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "project_type", err: fmt.Errorf(`ent: validator failed for field "Portfolio.project_type": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Status(); ok {
		if err := portfolio.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Portfolio.status": %w`, err)}
		}
	}
	if v, ok := pu.mutation.DemoURL(); ok {
		if err := portfolio.DemoURLValidator(v); err != nil {
			return &ValidationError{Name: "demo_url", err: fmt.Errorf(`ent: validator failed for field "Portfolio.demo_url": %w`, err)}
		}
	}
	if v, ok := pu.mutation.GithubURL(); ok {
		if err := portfolio.GithubURLValidator(v); err != nil {
			return &ValidationError{Name: "github_url", err: fmt.Errorf(`ent: validator failed for field "Portfolio.github_url": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Role(); ok {
		if err := portfolio.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Portfolio.role": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Duration(); ok {
		if err := portfolio.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "Portfolio.duration": %w`, err)}
		}
	}
	if v, ok := pu.mutation.GetClient(); ok {
		if err := portfolio.ClientValidator(v); err != nil {
			return &ValidationError{Name: "client", err: fmt.Errorf(`ent: validator failed for field "Portfolio.client": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (pu *PortfolioUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PortfolioUpdate {
	pu.modifiers = append(pu.modifiers, modifiers...)
	return pu
}

func (pu *PortfolioUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(portfolio.Table, portfolio.Columns, sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUint))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.DeletedAt(); ok {
		_spec.SetField(portfolio.FieldDeletedAt, field.TypeTime, value)
	}
	if pu.mutation.DeletedAtCleared() {
		_spec.ClearField(portfolio.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(portfolio.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.Title(); ok {
		_spec.SetField(portfolio.FieldTitle, field.TypeString, value)
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(portfolio.FieldDescription, field.TypeString, value)
	}
	if pu.mutation.DescriptionCleared() {
		_spec.ClearField(portfolio.FieldDescription, field.TypeString)
	}
	if value, ok := pu.mutation.CoverURL(); ok {
		_spec.SetField(portfolio.FieldCoverURL, field.TypeString, value)
	}
	if pu.mutation.CoverURLCleared() {
		_spec.ClearField(portfolio.FieldCoverURL, field.TypeString)
	}
	if value, ok := pu.mutation.ProjectType(); ok {
		_spec.SetField(portfolio.FieldProjectType, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.Status(); ok {
		_spec.SetField(portfolio.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.DemoURL(); ok {
		_spec.SetField(portfolio.FieldDemoURL, field.TypeString, value)
	}
	if pu.mutation.DemoURLCleared() {
		_spec.ClearField(portfolio.FieldDemoURL, field.TypeString)
	}
	if value, ok := pu.mutation.GithubURL(); ok {
		_spec.SetField(portfolio.FieldGithubURL, field.TypeString, value)
	}
	if pu.mutation.GithubURLCleared() {
		_spec.ClearField(portfolio.FieldGithubURL, field.TypeString)
	}
	if value, ok := pu.mutation.Featured(); ok {
		_spec.SetField(portfolio.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := pu.mutation.SortOrder(); ok {
		_spec.SetField(portfolio.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedSortOrder(); ok {
		_spec.AddField(portfolio.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Overview(); ok {
		_spec.SetField(portfolio.FieldOverview, field.TypeString, value)
	}
	if pu.mutation.OverviewCleared() {
		_spec.ClearField(portfolio.FieldOverview, field.TypeString)
	}
	if value, ok := pu.mutation.Role(); ok {
		_spec.SetField(portfolio.FieldRole, field.TypeString, value)
	}
	if pu.mutation.RoleCleared() {
		_spec.ClearField(portfolio.FieldRole, field.TypeString)
	}
	if value, ok := pu.mutation.Duration(); ok {
		_spec.SetField(portfolio.FieldDuration, field.TypeString, value)
	}
	if pu.mutation.DurationCleared() {
		_spec.ClearField(portfolio.FieldDuration, field.TypeString)
	}
	if value, ok := pu.mutation.GetClient(); ok {
		_spec.SetField(portfolio.FieldClient, field.TypeString, value)
	}
	if pu.mutation.ClientCleared() {
		_spec.ClearField(portfolio.FieldClient, field.TypeString)
	}
	if value, ok := pu.mutation.Challenge(); ok {
		_spec.SetField(portfolio.FieldChallenge, field.TypeString, value)
	}
	if pu.mutation.ChallengeCleared() {
		_spec.ClearField(portfolio.FieldChallenge, field.TypeString)
	}
	if value, ok := pu.mutation.Solution(); ok {
		_spec.SetField(portfolio.FieldSolution, field.TypeString, value)
	}
	if pu.mutation.SolutionCleared() {
		_spec.ClearField(portfolio.FieldSolution, field.TypeString)
	}
	if value, ok := pu.mutation.GalleryImages(); ok {
		_spec.SetField(portfolio.FieldGalleryImages, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.AppendedGalleryImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, portfolio.FieldGalleryImages, value)
		})
	}
	if pu.mutation.GalleryImagesCleared() {
		_spec.ClearField(portfolio.FieldGalleryImages, field.TypeJSON)
	}
	if pu.mutation.TechnologiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   portfolio.TechnologiesTable,
			Columns: []string{portfolio.TechnologiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedTechnologiesIDs(); len(nodes) > 0 && !pu.mutation.TechnologiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   portfolio.TechnologiesTable,
			Columns: []string{portfolio.TechnologiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.TechnologiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   portfolio.TechnologiesTable,
			Columns: []string{portfolio.TechnologiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(pu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portfolio.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PortfolioUpdateOne is the builder for updating a single Portfolio entity.
type PortfolioUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PortfolioMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeletedAt sets the "deleted_at" field.
func (puo *PortfolioUpdateOne) SetDeletedAt(t time.Time) *PortfolioUpdateOne {
	puo.mutation.SetDeletedAt(t)
	return puo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableDeletedAt(t *time.Time) *PortfolioUpdateOne {
	if t != nil {
		puo.SetDeletedAt(*t)
	}
	return puo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (puo *PortfolioUpdateOne) ClearDeletedAt() *PortfolioUpdateOne {
	puo.mutation.ClearDeletedAt()
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *PortfolioUpdateOne) SetUpdatedAt(t time.Time) *PortfolioUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetTitle sets the "title" field.
func (puo *PortfolioUpdateOne) SetTitle(s string) *PortfolioUpdateOne {
	puo.mutation.SetTitle(s)
	return puo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableTitle(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetTitle(*s)
	}
	return puo
}

// SetDescription sets the "description" field.
func (puo *PortfolioUpdateOne) SetDescription(s string) *PortfolioUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableDescription(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// ClearDescription clears the value of the "description" field.
func (puo *PortfolioUpdateOne) ClearDescription() *PortfolioUpdateOne {
	puo.mutation.ClearDescription()
	return puo
}

// SetCoverURL sets the "cover_url" field.
func (puo *PortfolioUpdateOne) SetCoverURL(s string) *PortfolioUpdateOne {
	puo.mutation.SetCoverURL(s)
	return puo
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableCoverURL(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetCoverURL(*s)
	}
	return puo
}

// ClearCoverURL clears the value of the "cover_url" field.
func (puo *PortfolioUpdateOne) ClearCoverURL() *PortfolioUpdateOne {
	puo.mutation.ClearCoverURL()
	return puo
}

// SetProjectType sets the "project_type" field.
func (puo *PortfolioUpdateOne) SetProjectType(pt portfolio.ProjectType) *PortfolioUpdateOne {
	puo.mutation.SetProjectType(pt)
	return puo
}

// SetNillableProjectType sets the "project_type" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableProjectType(pt *portfolio.ProjectType) *PortfolioUpdateOne {
	if pt != nil {
		puo.SetProjectType(*pt)
	}
	return puo
}

// SetStatus sets the "status" field.
func (puo *PortfolioUpdateOne) SetStatus(po portfolio.Status) *PortfolioUpdateOne {
	puo.mutation.SetStatus(po)
	return puo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableStatus(po *portfolio.Status) *PortfolioUpdateOne {
	if po != nil {
		puo.SetStatus(*po)
	}
	return puo
}

// SetDemoURL sets the "demo_url" field.
func (puo *PortfolioUpdateOne) SetDemoURL(s string) *PortfolioUpdateOne {
	puo.mutation.SetDemoURL(s)
	return puo
}

// SetNillableDemoURL sets the "demo_url" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableDemoURL(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetDemoURL(*s)
	}
	return puo
}

// ClearDemoURL clears the value of the "demo_url" field.
func (puo *PortfolioUpdateOne) ClearDemoURL() *PortfolioUpdateOne {
	puo.mutation.ClearDemoURL()
	return puo
}

// SetGithubURL sets the "github_url" field.
func (puo *PortfolioUpdateOne) SetGithubURL(s string) *PortfolioUpdateOne {
	puo.mutation.SetGithubURL(s)
	return puo
}

// SetNillableGithubURL sets the "github_url" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableGithubURL(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetGithubURL(*s)
	}
	return puo
}

// ClearGithubURL clears the value of the "github_url" field.
func (puo *PortfolioUpdateOne) ClearGithubURL() *PortfolioUpdateOne {
	puo.mutation.ClearGithubURL()
	return puo
}

// SetFeatured sets the "featured" field.
func (puo *PortfolioUpdateOne) SetFeatured(b bool) *PortfolioUpdateOne {
	puo.mutation.SetFeatured(b)
	return puo
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableFeatured(b *bool) *PortfolioUpdateOne {
	if b != nil {
		puo.SetFeatured(*b)
	}
	return puo
}

// SetSortOrder sets the "sort_order" field.
func (puo *PortfolioUpdateOne) SetSortOrder(i int) *PortfolioUpdateOne {
	puo.mutation.ResetSortOrder()
	puo.mutation.SetSortOrder(i)
	return puo
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableSortOrder(i *int) *PortfolioUpdateOne {
	if i != nil {
		puo.SetSortOrder(*i)
	}
	return puo
}

// AddSortOrder adds i to the "sort_order" field.
func (puo *PortfolioUpdateOne) AddSortOrder(i int) *PortfolioUpdateOne {
	puo.mutation.AddSortOrder(i)
	return puo
}

// SetOverview sets the "overview" field.
func (puo *PortfolioUpdateOne) SetOverview(s string) *PortfolioUpdateOne {
	puo.mutation.SetOverview(s)
	return puo
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableOverview(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetOverview(*s)
	}
	return puo
}

// ClearOverview clears the value of the "overview" field.
func (puo *PortfolioUpdateOne) ClearOverview() *PortfolioUpdateOne {
	puo.mutation.ClearOverview()
	return puo
}

// SetRole sets the "role" field.
func (puo *PortfolioUpdateOne) SetRole(s string) *PortfolioUpdateOne {
	puo.mutation.SetRole(s)
	return puo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableRole(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetRole(*s)
	}
	return puo
}

// ClearRole clears the value of the "role" field.
func (puo *PortfolioUpdateOne) ClearRole() *PortfolioUpdateOne {
	puo.mutation.ClearRole()
	return puo
}

// SetDuration sets the "duration" field.
func (puo *PortfolioUpdateOne) SetDuration(s string) *PortfolioUpdateOne {
	puo.mutation.SetDuration(s)
	return puo
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableDuration(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetDuration(*s)
	}
	return puo
}

// ClearDuration clears the value of the "duration" field.
func (puo *PortfolioUpdateOne) ClearDuration() *PortfolioUpdateOne {
	puo.mutation.ClearDuration()
	return puo
}

// SetClient sets the "client" field.
func (puo *PortfolioUpdateOne) SetClient(s string) *PortfolioUpdateOne {
	puo.mutation.SetClient(s)
	return puo
}

// SetNillableClient sets the "client" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableClient(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetClient(*s)
	}
	return puo
}

// ClearClient clears the value of the "client" field.
func (puo *PortfolioUpdateOne) ClearClient() *PortfolioUpdateOne {
	puo.mutation.ClearClient()
	return puo
}

// SetChallenge sets the "challenge" field.
func (puo *PortfolioUpdateOne) SetChallenge(s string) *PortfolioUpdateOne {
	puo.mutation.SetChallenge(s)
	return puo
}

// SetNillableChallenge sets the "challenge" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableChallenge(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetChallenge(*s)
	}
	return puo
}

// ClearChallenge clears the value of the "challenge" field.
func (puo *PortfolioUpdateOne) ClearChallenge() *PortfolioUpdateOne {
	puo.mutation.ClearChallenge()
	return puo
}

// SetSolution sets the "solution" field.
func (puo *PortfolioUpdateOne) SetSolution(s string) *PortfolioUpdateOne {
	puo.mutation.SetSolution(s)
	return puo
}

// SetNillableSolution sets the "solution" field if the given value is not nil.
func (puo *PortfolioUpdateOne) SetNillableSolution(s *string) *PortfolioUpdateOne {
	if s != nil {
		puo.SetSolution(*s)
	}
	return puo
}

// ClearSolution clears the value of the "solution" field.
func (puo *PortfolioUpdateOne) ClearSolution() *PortfolioUpdateOne {
	puo.mutation.ClearSolution()
	return puo
}

// SetGalleryImages sets the "gallery_images" field.
func (puo *PortfolioUpdateOne) SetGalleryImages(s []string) *PortfolioUpdateOne {
	puo.mutation.SetGalleryImages(s)
	return puo
}

// AppendGalleryImages appends s to the "gallery_images" field.
func (puo *PortfolioUpdateOne) AppendGalleryImages(s []string) *PortfolioUpdateOne {
	puo.mutation.AppendGalleryImages(s)
	return puo
}

// ClearGalleryImages clears the value of the "gallery_images" field.
func (puo *PortfolioUpdateOne) ClearGalleryImages() *PortfolioUpdateOne {
	puo.mutation.ClearGalleryImages()
	return puo
}

// AddTechnologyIDs adds the "technologies" edge to the PortfolioTechnology entity by IDs.
func (puo *PortfolioUpdateOne) AddTechnologyIDs(ids ...uint) *PortfolioUpdateOne {
	puo.mutation.AddTechnologyIDs(ids...)
	return puo
}

// AddTechnologies adds the "technologies" edges to the PortfolioTechnology entity.
func (puo *PortfolioUpdateOne) AddTechnologies(p ...*PortfolioTechnology) *PortfolioUpdateOne {
	ids := make([]uint, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddTechnologyIDs(ids...)
}

// Mutation returns the PortfolioMutation object of the builder.
func (puo *PortfolioUpdateOne) Mutation() *PortfolioMutation {
	return puo.mutation
}

// ClearTechnologies clears all "technologies" edges to the PortfolioTechnology entity.
func (puo *PortfolioUpdateOne) ClearTechnologies() *PortfolioUpdateOne {
	puo.mutation.ClearTechnologies()
	return puo
}

// RemoveTechnologyIDs removes the "technologies" edge to PortfolioTechnology entities by IDs.
func (puo *PortfolioUpdateOne) RemoveTechnologyIDs(ids ...uint) *PortfolioUpdateOne {
	puo.mutation.RemoveTechnologyIDs(ids...)
	return puo
}

// RemoveTechnologies removes "technologies" edges to PortfolioTechnology entities.
func (puo *PortfolioUpdateOne) RemoveTechnologies(p ...*PortfolioTechnology) *PortfolioUpdateOne {
	ids := make([]uint, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemoveTechnologyIDs(ids...)
}

// Where appends a list predicates to the PortfolioUpdate builder.
func (puo *PortfolioUpdateOne) Where(ps ...predicate.Portfolio) *PortfolioUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PortfolioUpdateOne) Select(field string, fields ...string) *PortfolioUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Portfolio entity.
func (puo *PortfolioUpdateOne) Save(ctx context.Context) (*Portfolio, error) {
	if err := puo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PortfolioUpdateOne) SaveX(ctx context.Context) *Portfolio {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PortfolioUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PortfolioUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PortfolioUpdateOne) defaults() error {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		if portfolio.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized portfolio.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := portfolio.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (puo *PortfolioUpdateOne) check() error {
	if v, ok := puo.mutation.Title(); ok {
		if err := portfolio.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Portfolio.title": %w`, err)}
		}
	}
	if v, ok := puo.mutation.ProjectType(); ok {
		if err := portfolio.ProjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "project_type", err: fmt.Errorf(`ent: validator failed for field "Portfolio.project_type": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Status(); ok {
		if err := portfolio.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Portfolio.status": %w`, err)}
		}
	}
	if v, ok := puo.mutation.DemoURL(); ok {
		if err := portfolio.DemoURLValidator(v); err != nil {
			return &ValidationError{Name: "demo_url", err: fmt.Errorf(`ent: validator failed for field "Portfolio.demo_url": %w`, err)}
		}
	}
	if v, ok := puo.mutation.GithubURL(); ok {
		if err := portfolio.GithubURLValidator(v); err != nil {
			return &ValidationError{Name: "github_url", err: fmt.Errorf(`ent: validator failed for field "Portfolio.github_url": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Role(); ok {
		if err := portfolio.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Portfolio.role": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Duration(); ok {
		if err := portfolio.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "Portfolio.duration": %w`, err)}
		}
	}
	if v, ok := puo.mutation.GetClient(); ok {
		if err := portfolio.ClientValidator(v); err != nil {
			return &ValidationError{Name: "client", err: fmt.Errorf(`ent: validator failed for field "Portfolio.client": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (puo *PortfolioUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PortfolioUpdateOne {
	puo.modifiers = append(puo.modifiers, modifiers...)
	return puo
}

func (puo *PortfolioUpdateOne) sqlSave(ctx context.Context) (_node *Portfolio, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(portfolio.Table, portfolio.Columns, sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUint))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Portfolio.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portfolio.FieldID)
		for _, f := range fields {
			if !portfolio.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != portfolio.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.DeletedAt(); ok {
		_spec.SetField(portfolio.FieldDeletedAt, field.TypeTime, value)
	}
	if puo.mutation.DeletedAtCleared() {
		_spec.ClearField(portfolio.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(portfolio.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.Title(); ok {
		_spec.SetField(portfolio.FieldTitle, field.TypeString, value)
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(portfolio.FieldDescription, field.TypeString, value)
	}
	if puo.mutation.DescriptionCleared() {
		_spec.ClearField(portfolio.FieldDescription, field.TypeString)
	}
	if value, ok := puo.mutation.CoverURL(); ok {
		_spec.SetField(portfolio.FieldCoverURL, field.TypeString, value)
	}
	if puo.mutation.CoverURLCleared() {
		_spec.ClearField(portfolio.FieldCoverURL, field.TypeString)
	}
	if value, ok := puo.mutation.ProjectType(); ok {
		_spec.SetField(portfolio.FieldProjectType, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.Status(); ok {
		_spec.SetField(portfolio.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.DemoURL(); ok {
		_spec.SetField(portfolio.FieldDemoURL, field.TypeString, value)
	}
	if puo.mutation.DemoURLCleared() {
		_spec.ClearField(portfolio.FieldDemoURL, field.TypeString)
	}
	if value, ok := puo.mutation.GithubURL(); ok {
		_spec.SetField(portfolio.FieldGithubURL, field.TypeString, value)
	}
	if puo.mutation.GithubURLCleared() {
		_spec.ClearField(portfolio.FieldGithubURL, field.TypeString)
	}
	if value, ok := puo.mutation.Featured(); ok {
		_spec.SetField(portfolio.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := puo.mutation.SortOrder(); ok {
		_spec.SetField(portfolio.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedSortOrder(); ok {
		_spec.AddField(portfolio.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Overview(); ok {
		_spec.SetField(portfolio.FieldOverview, field.TypeString, value)
	}
	if puo.mutation.OverviewCleared() {
		_spec.ClearField(portfolio.FieldOverview, field.TypeString)
	}
	if value, ok := puo.mutation.Role(); ok {
		_spec.SetField(portfolio.FieldRole, field.TypeString, value)
	}
	if puo.mutation.RoleCleared() {
		_spec.ClearField(portfolio.FieldRole, field.TypeString)
	}
	if value, ok := puo.mutation.Duration(); ok {
		_spec.SetField(portfolio.FieldDuration, field.TypeString, value)
	}
	if puo.mutation.DurationCleared() {
		_spec.ClearField(portfolio.FieldDuration, field.TypeString)
	}
	if value, ok := puo.mutation.GetClient(); ok {
		_spec.SetField(portfolio.FieldClient, field.TypeString, value)
	}
	if puo.mutation.ClientCleared() {
		_spec.ClearField(portfolio.FieldClient, field.TypeString)
	}
	if value, ok := puo.mutation.Challenge(); ok {
		_spec.SetField(portfolio.FieldChallenge, field.TypeString, value)
	}
	if puo.mutation.ChallengeCleared() {
		_spec.ClearField(portfolio.FieldChallenge, field.TypeString)
	}
	if value, ok := puo.mutation.Solution(); ok {
		_spec.SetField(portfolio.FieldSolution, field.TypeString, value)
	}
	if puo.mutation.SolutionCleared() {
		_spec.ClearField(portfolio.FieldSolution, field.TypeString)
	}
	if value, ok := puo.mutation.GalleryImages(); ok {
		_spec.SetField(portfolio.FieldGalleryImages, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.AppendedGalleryImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, portfolio.FieldGalleryImages, value)
		})
	}
	if puo.mutation.GalleryImagesCleared() {
		_spec.ClearField(portfolio.FieldGalleryImages, field.TypeJSON)
	}
	if puo.mutation.TechnologiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   portfolio.TechnologiesTable,
			Columns: []string{portfolio.TechnologiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedTechnologiesIDs(); len(nodes) > 0 && !puo.mutation.TechnologiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   portfolio.TechnologiesTable,
			Columns: []string{portfolio.TechnologiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.TechnologiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   portfolio.TechnologiesTable,
			Columns: []string{portfolio.TechnologiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(puo.modifiers...)
	_node = &Portfolio{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portfolio.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
