// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/portfolio"
	"github.com/anzhiyu-c/anheyu-app/ent/portfoliotechnology"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// PortfolioTechnologyUpdate is the builder for updating PortfolioTechnology entities.
type PortfolioTechnologyUpdate struct {
	config
	hooks     []Hook
	mutation  *PortfolioTechnologyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PortfolioTechnologyUpdate builder.
func (ptu *PortfolioTechnologyUpdate) Where(ps ...predicate.PortfolioTechnology) *PortfolioTechnologyUpdate {
	ptu.mutation.Where(ps...)
	return ptu
}

// SetDeletedAt sets the "deleted_at" field.
func (ptu *PortfolioTechnologyUpdate) SetDeletedAt(t time.Time) *PortfolioTechnologyUpdate {
	ptu.mutation.SetDeletedAt(t)
	return ptu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ptu *PortfolioTechnologyUpdate) SetNillableDeletedAt(t *time.Time) *PortfolioTechnologyUpdate {
	if t != nil {
		ptu.SetDeletedAt(*t)
	}
	return ptu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ptu *PortfolioTechnologyUpdate) ClearDeletedAt() *PortfolioTechnologyUpdate {
	ptu.mutation.ClearDeletedAt()
	return ptu
}

// SetUpdatedAt sets the "updated_at" field.
func (ptu *PortfolioTechnologyUpdate) SetUpdatedAt(t time.Time) *PortfolioTechnologyUpdate {
	ptu.mutation.SetUpdatedAt(t)
	return ptu
}

// SetTechnology sets the "technology" field.
func (ptu *PortfolioTechnologyUpdate) SetTechnology(s string) *PortfolioTechnologyUpdate {
	ptu.mutation.SetTechnology(s)
	return ptu
}

// SetNillableTechnology sets the "technology" field if the given value is not nil.
func (ptu *PortfolioTechnologyUpdate) SetNillableTechnology(s *string) *PortfolioTechnologyUpdate {
	if s != nil {
		ptu.SetTechnology(*s)
	}
	return ptu
}

// SetPortfolioID sets the "portfolio" edge to the Portfolio entity by ID.
func (ptu *PortfolioTechnologyUpdate) SetPortfolioID(id uint) *PortfolioTechnologyUpdate {
	ptu.mutation.SetPortfolioID(id)
	return ptu
}

// SetNillablePortfolioID sets the "portfolio" edge to the Portfolio entity by ID if the given value is not nil.
func (ptu *PortfolioTechnologyUpdate) SetNillablePortfolioID(id *uint) *PortfolioTechnologyUpdate {
	if id != nil {
		ptu = ptu.SetPortfolioID(*id)
	}
	return ptu
}

// SetPortfolio sets the "portfolio" edge to the Portfolio entity.
func (ptu *PortfolioTechnologyUpdate) SetPortfolio(p *Portfolio) *PortfolioTechnologyUpdate {
	return ptu.SetPortfolioID(p.ID)
}

// Mutation returns the PortfolioTechnologyMutation object of the builder.
func (ptu *PortfolioTechnologyUpdate) Mutation() *PortfolioTechnologyMutation {
	return ptu.mutation
}

// ClearPortfolio clears the "portfolio" edge to the Portfolio entity.
func (ptu *PortfolioTechnologyUpdate) ClearPortfolio() *PortfolioTechnologyUpdate {
	ptu.mutation.ClearPortfolio()
	return ptu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ptu *PortfolioTechnologyUpdate) Save(ctx context.Context) (int, error) {
	if err := ptu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, ptu.sqlSave, ptu.mutation, ptu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ptu *PortfolioTechnologyUpdate) SaveX(ctx context.Context) int {
	affected, err := ptu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ptu *PortfolioTechnologyUpdate) Exec(ctx context.Context) error {
	_, err := ptu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptu *PortfolioTechnologyUpdate) ExecX(ctx context.Context) {
	if err := ptu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ptu *PortfolioTechnologyUpdate) defaults() error {
	if _, ok := ptu.mutation.UpdatedAt(); !ok {
		if portfoliotechnology.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized portfoliotechnology.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := portfoliotechnology.UpdateDefaultUpdatedAt()
		ptu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ptu *PortfolioTechnologyUpdate) check() error {
	if v, ok := ptu.mutation.Technology(); ok {
		if err := portfoliotechnology.TechnologyValidator(v); err != nil {
			return &ValidationError{Name: "technology", err: fmt.Errorf(`ent: validator failed for field "PortfolioTechnology.technology": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ptu *PortfolioTechnologyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PortfolioTechnologyUpdate {
	ptu.modifiers = append(ptu.modifiers, modifiers...)
	return ptu
}

func (ptu *PortfolioTechnologyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ptu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(portfoliotechnology.Table, portfoliotechnology.Columns, sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint))
	if ps := ptu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ptu.mutation.DeletedAt(); ok {
		_spec.SetField(portfoliotechnology.FieldDeletedAt, field.TypeTime, value)
	}
	if ptu.mutation.DeletedAtCleared() {
		_spec.ClearField(portfoliotechnology.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ptu.mutation.UpdatedAt(); ok {
		_spec.SetField(portfoliotechnology.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ptu.mutation.Technology(); ok {
		_spec.SetField(portfoliotechnology.FieldTechnology, field.TypeString, value)
	}
	if ptu.mutation.PortfolioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliotechnology.PortfolioTable,
			Columns: []string{portfoliotechnology.PortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptu.mutation.PortfolioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliotechnology.PortfolioTable,
			Columns: []string{portfoliotechnology.PortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ptu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ptu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portfoliotechnology.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ptu.mutation.done = true
	return n, nil
}

// PortfolioTechnologyUpdateOne is the builder for updating a single PortfolioTechnology entity.
type PortfolioTechnologyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PortfolioTechnologyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeletedAt sets the "deleted_at" field.
func (ptuo *PortfolioTechnologyUpdateOne) SetDeletedAt(t time.Time) *PortfolioTechnologyUpdateOne {
	ptuo.mutation.SetDeletedAt(t)
	return ptuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ptuo *PortfolioTechnologyUpdateOne) SetNillableDeletedAt(t *time.Time) *PortfolioTechnologyUpdateOne {
	if t != nil {
		ptuo.SetDeletedAt(*t)
	}
	return ptuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ptuo *PortfolioTechnologyUpdateOne) ClearDeletedAt() *PortfolioTechnologyUpdateOne {
	ptuo.mutation.ClearDeletedAt()
	return ptuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ptuo *PortfolioTechnologyUpdateOne) SetUpdatedAt(t time.Time) *PortfolioTechnologyUpdateOne {
	ptuo.mutation.SetUpdatedAt(t)
	return ptuo
}

// SetTechnology sets the "technology" field.
func (ptuo *PortfolioTechnologyUpdateOne) SetTechnology(s string) *PortfolioTechnologyUpdateOne {
	ptuo.mutation.SetTechnology(s)
	return ptuo
}

// SetNillableTechnology sets the "technology" field if the given value is not nil.
func (ptuo *PortfolioTechnologyUpdateOne) SetNillableTechnology(s *string) *PortfolioTechnologyUpdateOne {
	if s != nil {
		ptuo.SetTechnology(*s)
	}
	return ptuo
}

// SetPortfolioID sets the "portfolio" edge to the Portfolio entity by ID.
func (ptuo *PortfolioTechnologyUpdateOne) SetPortfolioID(id uint) *PortfolioTechnologyUpdateOne {
	ptuo.mutation.SetPortfolioID(id)
	return ptuo
}

// SetNillablePortfolioID sets the "portfolio" edge to the Portfolio entity by ID if the given value is not nil.
func (ptuo *PortfolioTechnologyUpdateOne) SetNillablePortfolioID(id *uint) *PortfolioTechnologyUpdateOne {
	if id != nil {
		ptuo = ptuo.SetPortfolioID(*id)
	}
	return ptuo
}

// SetPortfolio sets the "portfolio" edge to the Portfolio entity.
func (ptuo *PortfolioTechnologyUpdateOne) SetPortfolio(p *Portfolio) *PortfolioTechnologyUpdateOne {
	return ptuo.SetPortfolioID(p.ID)
}

// Mutation returns the PortfolioTechnologyMutation object of the builder.
func (ptuo *PortfolioTechnologyUpdateOne) Mutation() *PortfolioTechnologyMutation {
	return ptuo.mutation
}

// ClearPortfolio clears the "portfolio" edge to the Portfolio entity.
func (ptuo *PortfolioTechnologyUpdateOne) ClearPortfolio() *PortfolioTechnologyUpdateOne {
	ptuo.mutation.ClearPortfolio()
	return ptuo
}

// Where appends a list predicates to the PortfolioTechnologyUpdate builder.
func (ptuo *PortfolioTechnologyUpdateOne) Where(ps ...predicate.PortfolioTechnology) *PortfolioTechnologyUpdateOne {
	ptuo.mutation.Where(ps...)
	return ptuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ptuo *PortfolioTechnologyUpdateOne) Select(field string, fields ...string) *PortfolioTechnologyUpdateOne {
	ptuo.fields = append([]string{field}, fields...)
	return ptuo
}

// Save executes the query and returns the updated PortfolioTechnology entity.
func (ptuo *PortfolioTechnologyUpdateOne) Save(ctx context.Context) (*PortfolioTechnology, error) {
	if err := ptuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ptuo.sqlSave, ptuo.mutation, ptuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ptuo *PortfolioTechnologyUpdateOne) SaveX(ctx context.Context) *PortfolioTechnology {
	node, err := ptuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ptuo *PortfolioTechnologyUpdateOne) Exec(ctx context.Context) error {
	_, err := ptuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptuo *PortfolioTechnologyUpdateOne) ExecX(ctx context.Context) {
	if err := ptuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ptuo *PortfolioTechnologyUpdateOne) defaults() error {
	if _, ok := ptuo.mutation.UpdatedAt(); !ok {
		if portfoliotechnology.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized portfoliotechnology.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := portfoliotechnology.UpdateDefaultUpdatedAt()
		ptuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ptuo *PortfolioTechnologyUpdateOne) check() error {
	if v, ok := ptuo.mutation.Technology(); ok {
		if err := portfoliotechnology.TechnologyValidator(v); err != nil {
			return &ValidationError{Name: "technology", err: fmt.Errorf(`ent: validator failed for field "PortfolioTechnology.technology": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ptuo *PortfolioTechnologyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PortfolioTechnologyUpdateOne {
	ptuo.modifiers = append(ptuo.modifiers, modifiers...)
	return ptuo
}

func (ptuo *PortfolioTechnologyUpdateOne) sqlSave(ctx context.Context) (_node *PortfolioTechnology, err error) {
	if err := ptuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(portfoliotechnology.Table, portfoliotechnology.Columns, sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint))
	id, ok := ptuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PortfolioTechnology.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ptuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portfoliotechnology.FieldID)
		for _, f := range fields {
			if !portfoliotechnology.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != portfoliotechnology.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ptuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ptuo.mutation.DeletedAt(); ok {
		_spec.SetField(portfoliotechnology.FieldDeletedAt, field.TypeTime, value)
	}
	if ptuo.mutation.DeletedAtCleared() {
		_spec.ClearField(portfoliotechnology.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ptuo.mutation.UpdatedAt(); ok {
		_spec.SetField(portfoliotechnology.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ptuo.mutation.Technology(); ok {
		_spec.SetField(portfoliotechnology.FieldTechnology, field.TypeString, value)
	}
	if ptuo.mutation.PortfolioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliotechnology.PortfolioTable,
			Columns: []string{portfoliotechnology.PortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptuo.mutation.PortfolioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliotechnology.PortfolioTable,
			Columns: []string{portfoliotechnology.PortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ptuo.modifiers...)
	_node = &PortfolioTechnology{config: ptuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ptuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portfoliotechnology.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ptuo.mutation.done = true
	return _node, nil
}
