// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/portfolio"
	"github.com/anzhiyu-c/anheyu-app/ent/portfoliotechnology"
)

// PortfolioCreate is the builder for creating a Portfolio entity.
type PortfolioCreate struct {
	config
	mutation *PortfolioMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (pc *PortfolioCreate) SetDeletedAt(t time.Time) *PortfolioCreate {
	pc.mutation.SetDeletedAt(t)
	return pc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableDeletedAt(t *time.Time) *PortfolioCreate {
	if t != nil {
		pc.SetDeletedAt(*t)
	}
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *PortfolioCreate) SetCreatedAt(t time.Time) *PortfolioCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableCreatedAt(t *time.Time) *PortfolioCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *PortfolioCreate) SetUpdatedAt(t time.Time) *PortfolioCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableUpdatedAt(t *time.Time) *PortfolioCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetTitle sets the "title" field.
func (pc *PortfolioCreate) SetTitle(s string) *PortfolioCreate {
	pc.mutation.SetTitle(s)
	return pc
}

// SetDescription sets the "description" field.
func (pc *PortfolioCreate) SetDescription(s string) *PortfolioCreate {
	pc.mutation.SetDescription(s)
	return pc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableDescription(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetDescription(*s)
	}
	return pc
}

// SetCoverURL sets the "cover_url" field.
func (pc *PortfolioCreate) SetCoverURL(s string) *PortfolioCreate {
	pc.mutation.SetCoverURL(s)
	return pc
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableCoverURL(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetCoverURL(*s)
	}
	return pc
}

// SetProjectType sets the "project_type" field.
func (pc *PortfolioCreate) SetProjectType(pt portfolio.ProjectType) *PortfolioCreate {
	pc.mutation.SetProjectType(pt)
	return pc
}

// SetNillableProjectType sets the "project_type" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableProjectType(pt *portfolio.ProjectType) *PortfolioCreate {
	if pt != nil {
		pc.SetProjectType(*pt)
	}
	return pc
}

// SetStatus sets the "status" field.
func (pc *PortfolioCreate) SetStatus(po portfolio.Status) *PortfolioCreate {
	pc.mutation.SetStatus(po)
	return pc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableStatus(po *portfolio.Status) *PortfolioCreate {
	if po != nil {
		pc.SetStatus(*po)
	}
	return pc
}

// SetDemoURL sets the "demo_url" field.
func (pc *PortfolioCreate) SetDemoURL(s string) *PortfolioCreate {
	pc.mutation.SetDemoURL(s)
	return pc
}

// SetNillableDemoURL sets the "demo_url" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableDemoURL(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetDemoURL(*s)
	}
	return pc
}

// SetGithubURL sets the "github_url" field.
func (pc *PortfolioCreate) SetGithubURL(s string) *PortfolioCreate {
	pc.mutation.SetGithubURL(s)
	return pc
}

// SetNillableGithubURL sets the "github_url" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableGithubURL(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetGithubURL(*s)
	}
	return pc
}

// SetFeatured sets the "featured" field.
func (pc *PortfolioCreate) SetFeatured(b bool) *PortfolioCreate {
	pc.mutation.SetFeatured(b)
	return pc
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableFeatured(b *bool) *PortfolioCreate {
	if b != nil {
		pc.SetFeatured(*b)
	}
	return pc
}

// SetSortOrder sets the "sort_order" field.
func (pc *PortfolioCreate) SetSortOrder(i int) *PortfolioCreate {
	pc.mutation.SetSortOrder(i)
	return pc
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableSortOrder(i *int) *PortfolioCreate {
	if i != nil {
		pc.SetSortOrder(*i)
	}
	return pc
}

// SetOverview sets the "overview" field.
func (pc *PortfolioCreate) SetOverview(s string) *PortfolioCreate {
	pc.mutation.SetOverview(s)
	return pc
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableOverview(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetOverview(*s)
	}
	return pc
}

// SetRole sets the "role" field.
func (pc *PortfolioCreate) SetRole(s string) *PortfolioCreate {
	pc.mutation.SetRole(s)
	return pc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableRole(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetRole(*s)
	}
	return pc
}

// SetDuration sets the "duration" field.
func (pc *PortfolioCreate) SetDuration(s string) *PortfolioCreate {
	pc.mutation.SetDuration(s)
	return pc
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableDuration(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetDuration(*s)
	}
	return pc
}

// SetClient sets the "client" field.
func (pc *PortfolioCreate) SetClient(s string) *PortfolioCreate {
	pc.mutation.SetClient(s)
	return pc
}

// SetNillableClient sets the "client" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableClient(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetClient(*s)
	}
	return pc
}

// SetChallenge sets the "challenge" field.
func (pc *PortfolioCreate) SetChallenge(s string) *PortfolioCreate {
	pc.mutation.SetChallenge(s)
	return pc
}

// SetNillableChallenge sets the "challenge" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableChallenge(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetChallenge(*s)
	}
	return pc
}

// SetSolution sets the "solution" field.
func (pc *PortfolioCreate) SetSolution(s string) *PortfolioCreate {
	pc.mutation.SetSolution(s)
	return pc
}

// SetNillableSolution sets the "solution" field if the given value is not nil.
func (pc *PortfolioCreate) SetNillableSolution(s *string) *PortfolioCreate {
	if s != nil {
		pc.SetSolution(*s)
	}
	return pc
}

// SetGalleryImages sets the "gallery_images" field.
func (pc *PortfolioCreate) SetGalleryImages(s []string) *PortfolioCreate {
	pc.mutation.SetGalleryImages(s)
	return pc
}

// SetID sets the "id" field.
func (pc *PortfolioCreate) SetID(u uint) *PortfolioCreate {
	pc.mutation.SetID(u)
	return pc
}

// AddTechnologyIDs adds the "technologies" edge to the PortfolioTechnology entity by IDs.
func (pc *PortfolioCreate) AddTechnologyIDs(ids ...uint) *PortfolioCreate {
	pc.mutation.AddTechnologyIDs(ids...)
	return pc
}

// AddTechnologies adds the "technologies" edges to the PortfolioTechnology entity.
func (pc *PortfolioCreate) AddTechnologies(p ...*PortfolioTechnology) *PortfolioCreate {
	ids := make([]uint, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pc.AddTechnologyIDs(ids...)
}

// Mutation returns the PortfolioMutation object of the builder.
func (pc *PortfolioCreate) Mutation() *PortfolioMutation {
	return pc.mutation
}

// Save creates the Portfolio in the database.
func (pc *PortfolioCreate) Save(ctx context.Context) (*Portfolio, error) {
	if err := pc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PortfolioCreate) SaveX(ctx context.Context) *Portfolio {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PortfolioCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PortfolioCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PortfolioCreate) defaults() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		if portfolio.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized portfolio.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := portfolio.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		if portfolio.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized portfolio.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := portfolio.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pc.mutation.ProjectType(); !ok {
		v := portfolio.DefaultProjectType
		pc.mutation.SetProjectType(v)
	}
	if _, ok := pc.mutation.Status(); !ok {
		v := portfolio.DefaultStatus
		pc.mutation.SetStatus(v)
	}
	if _, ok := pc.mutation.Featured(); !ok {
		v := portfolio.DefaultFeatured
		pc.mutation.SetFeatured(v)
	}
	if _, ok := pc.mutation.SortOrder(); !ok {
		v := portfolio.DefaultSortOrder
		pc.mutation.SetSortOrder(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pc *PortfolioCreate) check() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Portfolio.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Portfolio.updated_at"`)}
	}
	if _, ok := pc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Portfolio.title"`)}
	}
	if v, ok := pc.mutation.Title(); ok {
		if err := portfolio.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Portfolio.title": %w`, err)}
		}
	}
	if _, ok := pc.mutation.ProjectType(); !ok {
		return &ValidationError{Name: "project_type", err: errors.New(`ent: missing required field "Portfolio.project_type"`)}
	}
	if v, ok := pc.mutation.ProjectType(); ok {
		if err := portfolio.ProjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "project_type", err: fmt.Errorf(`ent: validator failed for field "Portfolio.project_type": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Portfolio.status"`)}
	}
	if v, ok := pc.mutation.Status(); ok {
		if err := portfolio.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Portfolio.status": %w`, err)}
		}
	}
	if v, ok := pc.mutation.DemoURL(); ok {
		if err := portfolio.DemoURLValidator(v); err != nil {
			return &ValidationError{Name: "demo_url", err: fmt.Errorf(`ent: validator failed for field "Portfolio.demo_url": %w`, err)}
		}
	}
	if v, ok := pc.mutation.GithubURL(); ok {
		if err := portfolio.GithubURLValidator(v); err != nil {
			return &ValidationError{Name: "github_url", err: fmt.Errorf(`ent: validator failed for field "Portfolio.github_url": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Featured(); !ok {
		return &ValidationError{Name: "featured", err: errors.New(`ent: missing required field "Portfolio.featured"`)}
	}
	if _, ok := pc.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Portfolio.sort_order"`)}
	}
	if v, ok := pc.mutation.Role(); ok {
		if err := portfolio.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Portfolio.role": %w`, err)}
		}
	}
	if v, ok := pc.mutation.Duration(); ok {
		if err := portfolio.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "Portfolio.duration": %w`, err)}
		}
	}
	if v, ok := pc.mutation.GetClient(); ok {
		if err := portfolio.ClientValidator(v); err != nil {
			return &ValidationError{Name: "client", err: fmt.Errorf(`ent: validator failed for field "Portfolio.client": %w`, err)}
		}
	}
	return nil
}

func (pc *PortfolioCreate) sqlSave(ctx context.Context) (*Portfolio, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PortfolioCreate) createSpec() (*Portfolio, *sqlgraph.CreateSpec) {
	var (
		_node = &Portfolio{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(portfolio.Table, sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUint))
	)
	_spec.OnConflict = pc.conflict
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.DeletedAt(); ok {
		_spec.SetField(portfolio.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(portfolio.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(portfolio.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.Title(); ok {
		_spec.SetField(portfolio.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := pc.mutation.Description(); ok {
		_spec.SetField(portfolio.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := pc.mutation.CoverURL(); ok {
		_spec.SetField(portfolio.FieldCoverURL, field.TypeString, value)
		_node.CoverURL = value
	}
	if value, ok := pc.mutation.ProjectType(); ok {
		_spec.SetField(portfolio.FieldProjectType, field.TypeEnum, value)
		_node.ProjectType = value
	}
	if value, ok := pc.mutation.Status(); ok {
		_spec.SetField(portfolio.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := pc.mutation.DemoURL(); ok {
		_spec.SetField(portfolio.FieldDemoURL, field.TypeString, value)
		_node.DemoURL = value
	}
	if value, ok := pc.mutation.GithubURL(); ok {
		_spec.SetField(portfolio.FieldGithubURL, field.TypeString, value)
		_node.GithubURL = value
	}
	if value, ok := pc.mutation.Featured(); ok {
		_spec.SetField(portfolio.FieldFeatured, field.TypeBool, value)
		_node.Featured = value
	}
	if value, ok := pc.mutation.SortOrder(); ok {
		_spec.SetField(portfolio.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := pc.mutation.Overview(); ok {
		_spec.SetField(portfolio.FieldOverview, field.TypeString, value)
		_node.Overview = value
	}
	if value, ok := pc.mutation.Role(); ok {
		_spec.SetField(portfolio.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := pc.mutation.Duration(); ok {
		_spec.SetField(portfolio.FieldDuration, field.TypeString, value)
		_node.Duration = value
	}
	if value, ok := pc.mutation.GetClient(); ok {
		_spec.SetField(portfolio.FieldClient, field.TypeString, value)
		_node.Client = value
	}
	if value, ok := pc.mutation.Challenge(); ok {
		_spec.SetField(portfolio.FieldChallenge, field.TypeString, value)
		_node.Challenge = value
	}
	if value, ok := pc.mutation.Solution(); ok {
		_spec.SetField(portfolio.FieldSolution, field.TypeString, value)
		_node.Solution = value
	}
	if value, ok := pc.mutation.GalleryImages(); ok {
		_spec.SetField(portfolio.FieldGalleryImages, field.TypeJSON, value)
		_node.GalleryImages = value
	}
	if nodes := pc.mutation.TechnologiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   portfolio.TechnologiesTable,
			Columns: []string{portfolio.TechnologiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfoliotechnology.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Portfolio.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PortfolioUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (pc *PortfolioCreate) OnConflict(opts ...sql.ConflictOption) *PortfolioUpsertOne {
	pc.conflict = opts
	return &PortfolioUpsertOne{
		create: pc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Portfolio.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pc *PortfolioCreate) OnConflictColumns(columns ...string) *PortfolioUpsertOne {
	pc.conflict = append(pc.conflict, sql.ConflictColumns(columns...))
	return &PortfolioUpsertOne{
		create: pc,
	}
}

type (
	// PortfolioUpsertOne is the builder for "upsert"-ing
	//  one Portfolio node.
	PortfolioUpsertOne struct {
		create *PortfolioCreate
	}

	// PortfolioUpsert is the "OnConflict" setter.
	PortfolioUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *PortfolioUpsert) SetDeletedAt(v time.Time) *PortfolioUpsert {
	u.Set(portfolio.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateDeletedAt() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PortfolioUpsert) ClearDeletedAt() *PortfolioUpsert {
	u.SetNull(portfolio.FieldDeletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PortfolioUpsert) SetUpdatedAt(v time.Time) *PortfolioUpsert {
	u.Set(portfolio.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateUpdatedAt() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldUpdatedAt)
	return u
}

// SetTitle sets the "title" field.
func (u *PortfolioUpsert) SetTitle(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateTitle() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *PortfolioUpsert) SetDescription(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateDescription() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *PortfolioUpsert) ClearDescription() *PortfolioUpsert {
	u.SetNull(portfolio.FieldDescription)
	return u
}

// SetCoverURL sets the "cover_url" field.
func (u *PortfolioUpsert) SetCoverURL(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldCoverURL, v)
	return u
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateCoverURL() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldCoverURL)
	return u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (u *PortfolioUpsert) ClearCoverURL() *PortfolioUpsert {
	u.SetNull(portfolio.FieldCoverURL)
	return u
}

// SetProjectType sets the "project_type" field.
func (u *PortfolioUpsert) SetProjectType(v portfolio.ProjectType) *PortfolioUpsert {
	u.Set(portfolio.FieldProjectType, v)
	return u
}

// UpdateProjectType sets the "project_type" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateProjectType() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldProjectType)
	return u
}

// SetStatus sets the "status" field.
func (u *PortfolioUpsert) SetStatus(v portfolio.Status) *PortfolioUpsert {
	u.Set(portfolio.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateStatus() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldStatus)
	return u
}

// SetDemoURL sets the "demo_url" field.
func (u *PortfolioUpsert) SetDemoURL(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldDemoURL, v)
	return u
}

// UpdateDemoURL sets the "demo_url" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateDemoURL() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldDemoURL)
	return u
}

// ClearDemoURL clears the value of the "demo_url" field.
func (u *PortfolioUpsert) ClearDemoURL() *PortfolioUpsert {
	u.SetNull(portfolio.FieldDemoURL)
	return u
}

// SetGithubURL sets the "github_url" field.
func (u *PortfolioUpsert) SetGithubURL(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldGithubURL, v)
	return u
}

// UpdateGithubURL sets the "github_url" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateGithubURL() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldGithubURL)
	return u
}

// ClearGithubURL clears the value of the "github_url" field.
func (u *PortfolioUpsert) ClearGithubURL() *PortfolioUpsert {
	u.SetNull(portfolio.FieldGithubURL)
	return u
}

// SetFeatured sets the "featured" field.
func (u *PortfolioUpsert) SetFeatured(v bool) *PortfolioUpsert {
	u.Set(portfolio.FieldFeatured, v)
	return u
}

// UpdateFeatured sets the "featured" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateFeatured() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldFeatured)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *PortfolioUpsert) SetSortOrder(v int) *PortfolioUpsert {
	u.Set(portfolio.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateSortOrder() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PortfolioUpsert) AddSortOrder(v int) *PortfolioUpsert {
	u.Add(portfolio.FieldSortOrder, v)
	return u
}

// SetOverview sets the "overview" field.
func (u *PortfolioUpsert) SetOverview(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldOverview, v)
	return u
}

// UpdateOverview sets the "overview" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateOverview() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldOverview)
	return u
}

// ClearOverview clears the value of the "overview" field.
func (u *PortfolioUpsert) ClearOverview() *PortfolioUpsert {
	u.SetNull(portfolio.FieldOverview)
	return u
}

// SetRole sets the "role" field.
func (u *PortfolioUpsert) SetRole(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateRole() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldRole)
	return u
}

// ClearRole clears the value of the "role" field.
func (u *PortfolioUpsert) ClearRole() *PortfolioUpsert {
	u.SetNull(portfolio.FieldRole)
	return u
}

// SetDuration sets the "duration" field.
func (u *PortfolioUpsert) SetDuration(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldDuration, v)
	return u
}

// UpdateDuration sets the "duration" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateDuration() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldDuration)
	return u
}

// ClearDuration clears the value of the "duration" field.
func (u *PortfolioUpsert) ClearDuration() *PortfolioUpsert {
	u.SetNull(portfolio.FieldDuration)
	return u
}

// SetClient sets the "client" field.
func (u *PortfolioUpsert) SetClient(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldClient, v)
	return u
}

// UpdateClient sets the "client" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateClient() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldClient)
	return u
}

// ClearClient clears the value of the "client" field.
func (u *PortfolioUpsert) ClearClient() *PortfolioUpsert {
	u.SetNull(portfolio.FieldClient)
	return u
}

// SetChallenge sets the "challenge" field.
func (u *PortfolioUpsert) SetChallenge(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldChallenge, v)
	return u
}

// UpdateChallenge sets the "challenge" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateChallenge() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldChallenge)
	return u
}

// ClearChallenge clears the value of the "challenge" field.
func (u *PortfolioUpsert) ClearChallenge() *PortfolioUpsert {
	u.SetNull(portfolio.FieldChallenge)
	return u
}

// SetSolution sets the "solution" field.
func (u *PortfolioUpsert) SetSolution(v string) *PortfolioUpsert {
	u.Set(portfolio.FieldSolution, v)
	return u
}

// UpdateSolution sets the "solution" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateSolution() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldSolution)
	return u
}

// ClearSolution clears the value of the "solution" field.
func (u *PortfolioUpsert) ClearSolution() *PortfolioUpsert {
	u.SetNull(portfolio.FieldSolution)
	return u
}

// SetGalleryImages sets the "gallery_images" field.
func (u *PortfolioUpsert) SetGalleryImages(v []string) *PortfolioUpsert {
	u.Set(portfolio.FieldGalleryImages, v)
	return u
}

// UpdateGalleryImages sets the "gallery_images" field to the value that was provided on create.
func (u *PortfolioUpsert) UpdateGalleryImages() *PortfolioUpsert {
	u.SetExcluded(portfolio.FieldGalleryImages)
	return u
}

// ClearGalleryImages clears the value of the "gallery_images" field.
func (u *PortfolioUpsert) ClearGalleryImages() *PortfolioUpsert {
	u.SetNull(portfolio.FieldGalleryImages)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Portfolio.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(portfolio.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PortfolioUpsertOne) UpdateNewValues() *PortfolioUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(portfolio.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(portfolio.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Portfolio.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PortfolioUpsertOne) Ignore() *PortfolioUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PortfolioUpsertOne) DoNothing() *PortfolioUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PortfolioCreate.OnConflict
// documentation for more info.
func (u *PortfolioUpsertOne) Update(set func(*PortfolioUpsert)) *PortfolioUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PortfolioUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PortfolioUpsertOne) SetDeletedAt(v time.Time) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateDeletedAt() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PortfolioUpsertOne) ClearDeletedAt() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PortfolioUpsertOne) SetUpdatedAt(v time.Time) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateUpdatedAt() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTitle sets the "title" field.
func (u *PortfolioUpsertOne) SetTitle(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateTitle() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *PortfolioUpsertOne) SetDescription(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateDescription() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PortfolioUpsertOne) ClearDescription() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearDescription()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *PortfolioUpsertOne) SetCoverURL(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateCoverURL() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateCoverURL()
	})
}

// ClearCoverURL clears the value of the "cover_url" field.
func (u *PortfolioUpsertOne) ClearCoverURL() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearCoverURL()
	})
}

// SetProjectType sets the "project_type" field.
func (u *PortfolioUpsertOne) SetProjectType(v portfolio.ProjectType) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetProjectType(v)
	})
}

// UpdateProjectType sets the "project_type" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateProjectType() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateProjectType()
	})
}

// SetStatus sets the "status" field.
func (u *PortfolioUpsertOne) SetStatus(v portfolio.Status) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateStatus() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateStatus()
	})
}

// SetDemoURL sets the "demo_url" field.
func (u *PortfolioUpsertOne) SetDemoURL(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetDemoURL(v)
	})
}

// UpdateDemoURL sets the "demo_url" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateDemoURL() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateDemoURL()
	})
}

// ClearDemoURL clears the value of the "demo_url" field.
func (u *PortfolioUpsertOne) ClearDemoURL() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearDemoURL()
	})
}

// SetGithubURL sets the "github_url" field.
func (u *PortfolioUpsertOne) SetGithubURL(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetGithubURL(v)
	})
}

// UpdateGithubURL sets the "github_url" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateGithubURL() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateGithubURL()
	})
}

// ClearGithubURL clears the value of the "github_url" field.
func (u *PortfolioUpsertOne) ClearGithubURL() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearGithubURL()
	})
}

// SetFeatured sets the "featured" field.
func (u *PortfolioUpsertOne) SetFeatured(v bool) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetFeatured(v)
	})
}

// UpdateFeatured sets the "featured" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateFeatured() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateFeatured()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PortfolioUpsertOne) SetSortOrder(v int) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PortfolioUpsertOne) AddSortOrder(v int) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateSortOrder() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateSortOrder()
	})
}

// SetOverview sets the "overview" field.
func (u *PortfolioUpsertOne) SetOverview(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetOverview(v)
	})
}

// UpdateOverview sets the "overview" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateOverview() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateOverview()
	})
}

// ClearOverview clears the value of the "overview" field.
func (u *PortfolioUpsertOne) ClearOverview() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearOverview()
	})
}

// SetRole sets the "role" field.
func (u *PortfolioUpsertOne) SetRole(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateRole() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateRole()
	})
}

// ClearRole clears the value of the "role" field.
func (u *PortfolioUpsertOne) ClearRole() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearRole()
	})
}

// SetDuration sets the "duration" field.
func (u *PortfolioUpsertOne) SetDuration(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetDuration(v)
	})
}

// UpdateDuration sets the "duration" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateDuration() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateDuration()
	})
}

// ClearDuration clears the value of the "duration" field.
func (u *PortfolioUpsertOne) ClearDuration() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearDuration()
	})
}

// SetClient sets the "client" field.
func (u *PortfolioUpsertOne) SetClient(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetClient(v)
	})
}

// UpdateClient sets the "client" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateClient() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateClient()
	})
}

// ClearClient clears the value of the "client" field.
func (u *PortfolioUpsertOne) ClearClient() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearClient()
	})
}

// SetChallenge sets the "challenge" field.
func (u *PortfolioUpsertOne) SetChallenge(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetChallenge(v)
	})
}

// UpdateChallenge sets the "challenge" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateChallenge() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateChallenge()
	})
}

// ClearChallenge clears the value of the "challenge" field.
func (u *PortfolioUpsertOne) ClearChallenge() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearChallenge()
	})
}

// SetSolution sets the "solution" field.
func (u *PortfolioUpsertOne) SetSolution(v string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetSolution(v)
	})
}

// UpdateSolution sets the "solution" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateSolution() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateSolution()
	})
}

// ClearSolution clears the value of the "solution" field.
func (u *PortfolioUpsertOne) ClearSolution() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearSolution()
	})
}

// SetGalleryImages sets the "gallery_images" field.
func (u *PortfolioUpsertOne) SetGalleryImages(v []string) *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetGalleryImages(v)
	})
}

// UpdateGalleryImages sets the "gallery_images" field to the value that was provided on create.
func (u *PortfolioUpsertOne) UpdateGalleryImages() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateGalleryImages()
	})
}

// ClearGalleryImages clears the value of the "gallery_images" field.
func (u *PortfolioUpsertOne) ClearGalleryImages() *PortfolioUpsertOne {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearGalleryImages()
	})
}

// Exec executes the query.
func (u *PortfolioUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PortfolioCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PortfolioUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PortfolioUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PortfolioUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PortfolioCreateBulk is the builder for creating many Portfolio entities in bulk.
type PortfolioCreateBulk struct {
	config
	err      error
	builders []*PortfolioCreate
	conflict []sql.ConflictOption
}

// Save creates the Portfolio entities in the database.
func (pcb *PortfolioCreateBulk) Save(ctx context.Context) ([]*Portfolio, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Portfolio, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PortfolioMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PortfolioCreateBulk) SaveX(ctx context.Context) []*Portfolio {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PortfolioCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PortfolioCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Portfolio.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PortfolioUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (pcb *PortfolioCreateBulk) OnConflict(opts ...sql.ConflictOption) *PortfolioUpsertBulk {
	pcb.conflict = opts
	return &PortfolioUpsertBulk{
		create: pcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Portfolio.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pcb *PortfolioCreateBulk) OnConflictColumns(columns ...string) *PortfolioUpsertBulk {
	pcb.conflict = append(pcb.conflict, sql.ConflictColumns(columns...))
	return &PortfolioUpsertBulk{
		create: pcb,
	}
}

// PortfolioUpsertBulk is the builder for "upsert"-ing
// a bulk of Portfolio nodes.
type PortfolioUpsertBulk struct {
	create *PortfolioCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Portfolio.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(portfolio.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PortfolioUpsertBulk) UpdateNewValues() *PortfolioUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(portfolio.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(portfolio.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Portfolio.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PortfolioUpsertBulk) Ignore() *PortfolioUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PortfolioUpsertBulk) DoNothing() *PortfolioUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PortfolioCreateBulk.OnConflict
// documentation for more info.
func (u *PortfolioUpsertBulk) Update(set func(*PortfolioUpsert)) *PortfolioUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PortfolioUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PortfolioUpsertBulk) SetDeletedAt(v time.Time) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateDeletedAt() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PortfolioUpsertBulk) ClearDeletedAt() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PortfolioUpsertBulk) SetUpdatedAt(v time.Time) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateUpdatedAt() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTitle sets the "title" field.
func (u *PortfolioUpsertBulk) SetTitle(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateTitle() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *PortfolioUpsertBulk) SetDescription(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateDescription() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PortfolioUpsertBulk) ClearDescription() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearDescription()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *PortfolioUpsertBulk) SetCoverURL(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateCoverURL() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateCoverURL()
	})
}

// ClearCoverURL clears the value of the "cover_url" field.
func (u *PortfolioUpsertBulk) ClearCoverURL() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearCoverURL()
	})
}

// SetProjectType sets the "project_type" field.
func (u *PortfolioUpsertBulk) SetProjectType(v portfolio.ProjectType) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetProjectType(v)
	})
}

// UpdateProjectType sets the "project_type" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateProjectType() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateProjectType()
	})
}

// SetStatus sets the "status" field.
func (u *PortfolioUpsertBulk) SetStatus(v portfolio.Status) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateStatus() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateStatus()
	})
}

// SetDemoURL sets the "demo_url" field.
func (u *PortfolioUpsertBulk) SetDemoURL(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetDemoURL(v)
	})
}

// UpdateDemoURL sets the "demo_url" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateDemoURL() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateDemoURL()
	})
}

// ClearDemoURL clears the value of the "demo_url" field.
func (u *PortfolioUpsertBulk) ClearDemoURL() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearDemoURL()
	})
}

// SetGithubURL sets the "github_url" field.
func (u *PortfolioUpsertBulk) SetGithubURL(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetGithubURL(v)
	})
}

// UpdateGithubURL sets the "github_url" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateGithubURL() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateGithubURL()
	})
}

// ClearGithubURL clears the value of the "github_url" field.
func (u *PortfolioUpsertBulk) ClearGithubURL() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearGithubURL()
	})
}

// SetFeatured sets the "featured" field.
func (u *PortfolioUpsertBulk) SetFeatured(v bool) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetFeatured(v)
	})
}

// UpdateFeatured sets the "featured" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateFeatured() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateFeatured()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PortfolioUpsertBulk) SetSortOrder(v int) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PortfolioUpsertBulk) AddSortOrder(v int) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateSortOrder() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateSortOrder()
	})
}

// SetOverview sets the "overview" field.
func (u *PortfolioUpsertBulk) SetOverview(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetOverview(v)
	})
}

// UpdateOverview sets the "overview" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateOverview() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateOverview()
	})
}

// ClearOverview clears the value of the "overview" field.
func (u *PortfolioUpsertBulk) ClearOverview() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearOverview()
	})
}

// SetRole sets the "role" field.
func (u *PortfolioUpsertBulk) SetRole(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateRole() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateRole()
	})
}

// ClearRole clears the value of the "role" field.
func (u *PortfolioUpsertBulk) ClearRole() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearRole()
	})
}

// SetDuration sets the "duration" field.
func (u *PortfolioUpsertBulk) SetDuration(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetDuration(v)
	})
}

// UpdateDuration sets the "duration" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateDuration() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateDuration()
	})
}

// ClearDuration clears the value of the "duration" field.
func (u *PortfolioUpsertBulk) ClearDuration() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearDuration()
	})
}

// SetClient sets the "client" field.
func (u *PortfolioUpsertBulk) SetClient(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetClient(v)
	})
}

// UpdateClient sets the "client" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateClient() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateClient()
	})
}

// ClearClient clears the value of the "client" field.
func (u *PortfolioUpsertBulk) ClearClient() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearClient()
	})
}

// SetChallenge sets the "challenge" field.
func (u *PortfolioUpsertBulk) SetChallenge(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetChallenge(v)
	})
}

// UpdateChallenge sets the "challenge" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateChallenge() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateChallenge()
	})
}

// ClearChallenge clears the value of the "challenge" field.
func (u *PortfolioUpsertBulk) ClearChallenge() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearChallenge()
	})
}

// SetSolution sets the "solution" field.
func (u *PortfolioUpsertBulk) SetSolution(v string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetSolution(v)
	})
}

// UpdateSolution sets the "solution" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateSolution() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateSolution()
	})
}

// ClearSolution clears the value of the "solution" field.
func (u *PortfolioUpsertBulk) ClearSolution() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearSolution()
	})
}

// SetGalleryImages sets the "gallery_images" field.
func (u *PortfolioUpsertBulk) SetGalleryImages(v []string) *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.SetGalleryImages(v)
	})
}

// UpdateGalleryImages sets the "gallery_images" field to the value that was provided on create.
func (u *PortfolioUpsertBulk) UpdateGalleryImages() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.UpdateGalleryImages()
	})
}

// ClearGalleryImages clears the value of the "gallery_images" field.
func (u *PortfolioUpsertBulk) ClearGalleryImages() *PortfolioUpsertBulk {
	return u.Update(func(s *PortfolioUpsert) {
		s.ClearGalleryImages()
	})
}

// Exec executes the query.
func (u *PortfolioUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PortfolioCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PortfolioCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PortfolioUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
